### ISSUE TITLE
oan-v1.1 breaks mining solo pool

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion#1103]
I've been running a solo pool (from https://github.com/aionnetwork/aion_miner) for a very long time, but unfortunately the new version oan-v1.1 breaks its usage. In v1.0 it still worked fine. The error message can be seen below, I would really appreciate a fix as I'd like to continue solo mining. Will switch back to using oan-v1.0 for now.

```
2019-12-19 08:51:50 [Pool] [aion] (Thread 1) No rewardRecipients have been setup which means no fees will be taken
buffer.js:183
    throw new TypeError(kFromErrorMsg);
    ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at Object.exports.bignumFromBitsHex (/home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/util.js:371:20)
    at new BlockTemplate (/home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/blockTemplate.js:60:14)
    at JobManager.processTemplate (/home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/jobManager.js:191:32)
    at /home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/pool.js:601:62
    at itemFinished (/home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:162:36)
    at /home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:175:17
    at parseJson (/home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:95:17)
2019-12-19 08:51:50 [Master] [PoolSpawner] Fork 0 died, spawning replacement worker...
```

**Comment by jeff-aion** [comment]
We are doing some work to formalize our RPCs and partially-automate their maintenance so I suspect that is to blame for this problem.

Additionally, we are moving to a strategy of making more frequent, smaller optional updates, so this might not be in our next update but we will investigate for a release, soon.  There should be no problem staying on 1.0 until a release fixes this.

@dev-dennis-guye can you look into this when you are back?

**Comment by JimVanEeden** [comment]
This still is an issue with oan v1.3, and now it bums me out because I have to upgrade so I can't solo mine until this is fixed.

**Comment by zzgang** [comment]
it is still a issue  now.

**Comment by zzgang** [comment]
It is still an issue now!

**Comment by zzgang** [comment]
The reason:

The method getblocktemplate returns an error result:

response: { code: -1, message: 'no mining block template ' }

**Comment by AionMiner** [comment]
You can solo mine using the aion_pool2 software. The trick is to just disable payouts within the config by setting the two instances of paymentProcessing enabled to false.

The hardware requirements listed within the setup guides are assuming for hundreds of connections.

Here it is running alongside the v1.3 Java Kernel on a 4 core CPU with 8GB DDR3 RAM and 120GB SSD (with my miner connected):

![aion_pool2](https://user-images.githubusercontent.com/39248106/74584516-d1f5a880-501e-11ea-8530-347fbc688d60.png)
