### ISSUE TITLE
ERROR P2P  [p2p-in]: Could not read buffer.

### ISSUE THREAD

**Issue by AionMiner** [aionnetwork/aion#1161]
## Description

ERROR P2P appearing frequently in kernel output since v1.6

```
20-12-10 15:26:28.225 ERROR P2P  [p2p-in]: Could not read buffer.
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.aion.p2p.impl1.P2pMgr.readBuffer(P2pMgr.java:738)
	at org.aion.p2p.impl1.P2pMgr.checkSelector(P2pMgr.java:593)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

Similar error notice looks to have been suppressed previously, as per closed issue https://github.com/aionnetwork/aion/issues/357

Log config is default:

```
<log>
    <!--Enable/Disable logback service; if disabled, output will not be logged.-->
    <log-file>true</log-file>
    <!--Sets the physical location on disk where log files will be stored.-->
    <log-path>log</log-path>
    <DB>WARN</DB>
    <GEN>INFO</GEN>
    <VM>ERROR</VM>
    <SYNC>INFO</SYNC>
    <CONS>INFO</CONS>
    <TXPOOL>WARN</TXPOOL>
    <API>INFO</API>
    <ROOT>WARN</ROOT>
    <P2P>INFO</P2P>
    <TX>WARN</TX>
</log>
```

## System Information

I'm running:

- **Which Aion version?**: 1.6.1.0528110
- **Which operating system?**: Linux
- **Which distributor and version?**: Ubuntu 20.10
- **How installed?**: via binaries
- **Are you fully synchronized?**: yes
- **Did you try to restart the node?**: yes

**Comment by AionJayT** [comment]
Thanks for the report. We will suppress the log to the DEBUG level.
