### ISSUE TITLE
Problem syncing after upgrade to 1.6.2

### ISSUE THREAD

**Issue by jcvernaleo** [aionnetwork/aion#1164]
## Description

We had some aion nodes running 1.5.1 pre hardfork.  They seemed to stay in sync/continue to process blocks with no problem.  We attempted to upgrade to 1.6.2 at which point the nodes add a few blocks and then stop adding blocks with this error:
```
(node) 20-12-17 17:20:50.599 DEBUG SYNC [sync-gb-18]: <get-bodies from-num=7441451 to-num=7441480 node=4bf296>
(node) 20-12-17 17:20:50.603 ERROR SYNC [sync-ib]: <import-block throw> 
(node) java.lang.ClassCastException: class org.aion.rlp.SharedRLPItem cannot be cast to class org.aion.rlp.SharedRLPList (org.aion.rlp.SharedRLPItem and org.aion.rlp.SharedRLPList are in unnamed module of loader 'app')
(node) 	at org.aion.zero.impl.db.FvmContractDetails.decodeAtRoot(FvmContractDetails.java:256)
(node) 	at org.aion.zero.impl.db.DetailsDataStore.getSnapshot(DetailsDataStore.java:85)
(node) 	at org.aion.zero.impl.db.AionRepositoryImpl.getContractDetails(AionRepositoryImpl.java:725)
(node) 	at org.aion.zero.impl.db.AionRepositoryImpl.getContractDetails(AionRepositoryImpl.java:90)
(node) 	at org.aion.zero.impl.db.AionRepositoryCache.getAccountStateFromParent(AionRepositoryCache.java:215)
(node) 	at org.aion.zero.impl.db.AionRepositoryCache.getAccountStateFromParent(AionRepositoryCache.java:204)
(node) 	at org.aion.zero.impl.db.AionRepositoryCache.getLocalAccountState(AionRepositoryCache.java:100)
(node) 	at org.aion.zero.impl.db.AionRepositoryCache.getAccountState(AionRepositoryCache.java:88)
(node) 	at org.aion.zero.impl.vm.common.BulkExecutor.getInternalVmType(BulkExecutor.java:585)
(node) 	at org.aion.zero.impl.vm.common.BulkExecutor.destinationIsAvmContract(BulkExecutor.java:606)
(node) 	at org.aion.zero.impl.vm.common.BulkExecutor.transactionIsForAionVirtualMachine(BulkExecutor.java:529)
(node) 	at org.aion.zero.impl.vm.common.BulkExecutor.executeInternal(BulkExecutor.java:226)
(node) 	at org.aion.zero.impl.vm.common.BulkExecutor.executeAllTransactionsInBlock(BulkExecutor.java:102)
(node) 	at org.aion.zero.impl.blockchain.AionBlockchainImpl.applyBlock(AionBlockchainImpl.java:1894)
(node) 	at org.aion.zero.impl.blockchain.AionBlockchainImpl.processBlock(AionBlockchainImpl.java:1796)
(node) 	at org.aion.zero.impl.blockchain.AionBlockchainImpl.add(AionBlockchainImpl.java:1538)
(node) 	at org.aion.zero.impl.blockchain.AionBlockchainImpl.tryToConnectAndFetchSummary(AionBlockchainImpl.java:1032)
(node) 	at org.aion.zero.impl.blockchain.AionBlockchainImpl.tryToConnectWithTimedExecution(AionBlockchainImpl.java:948)
(node) 	at org.aion.zero.impl.blockchain.AionBlockchainImpl.tryToConnect(AionBlockchainImpl.java:899)
(node) 	at org.aion.zero.impl.sync.TaskImportBlocks.processBatch(TaskImportBlocks.java:154)
(node) 	at org.aion.zero.impl.sync.TaskImportBlocks.importBlocks(TaskImportBlocks.java:56)
(node) 	at org.aion.zero.impl.sync.SyncMgr.lambda$filterBlocks$6(SyncMgr.java:431)
(node) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
(node) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
(node) 	at java.base/java.lang.Thread.run(Thread.java:834)
```

If we roll back to 1.5.1 (pre-fork) it starts processing blocks again just fine.  At the point of the hardfork we once again moved to 1.6.1 at which point we got a few new blocks and then back to that error.

Any ideas on how to get 1.6.2 working again?

## System Information

I'm running:

- **Which Aion version?**: 1.6.2
- **Which operating system?**: Linux
- **Which distributor and version?**: Ubuntu 16.04
- **How installed?**: via binaries 
- **Are you fully synchronized?**: no / yes (not any more and that is the problem).
- **Did you try to restart the node?**: yes

**Comment by AionJayT** [comment]
After checked the setup. We suspect the data serialize update cause the issue in LevelDB. Will investigate the issue.

**Comment by jcvernaleo** [comment]
We've long since fully resynced from scratch without issue so I think this can be safely closed.
