### ISSUE TITLE
InterruptedException in P2pMgr$TaskWrite when shutting-down the kernel

### ISSUE THREAD

**Issue by AionJayT** [aionnetwork/aion#117]
testing kernel version - 0.1.13.1daf22a

Sync the node with testnet to the highest block and then shutting down, got this message.

18-03-05 15:38:01.574 INFO  GEN  [Shutdown]: <shutdown-sync-mgr>
java.lang.InterruptedException
18-03-05 15:38:01.576 INFO  GEN  [Shutdown]: <shutdown-p2p-mgr>
18-03-05 15:38:01.576 INFO  GEN  [Shutdown]: TransactionExecThread shutting down...
18-03-05 15:38:01.576 INFO  GEN  [Shutdown]: TransactionExecThread waiting termination.
18-03-05 15:38:01.576 INFO  GEN  [Shutdown]: TransactionExecThread shutdown... Finished!
18-03-05 15:38:01.577 INFO  GEN  [Shutdown]: <shutdown-tx>
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2037)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2114)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432).
        at org.aion.p2p.impl.P2pMgr$TaskWrite.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
...18-03-05 15:38:05.578 INFO  GEN  [Shutdown]: shutting down consensus...
18-03-05 15:38:05.578 INFO  GEN  [Shutdown]: shutdown consensus... Done!
18-03-05 15:38:05.578 INFO  GEN  [Shutdown]: shutting down DB...
18-03-05 15:38:05.579 INFO  GEN  [Shutdown]: details DB closed.
18-03-05 15:38:05.590 INFO  GEN  [Shutdown]: state DB closed.
18-03-05 15:38:05.590 INFO  GEN  [Shutdown]: transaction DB closed.
18-03-05 15:38:05.615 INFO  GEN  [Shutdown]: block DB closed.
18-03-05 15:38:05.615 INFO  GEN  [Shutdown]: shutdown DB... Done!

**Comment by aion-6368726973** [comment]
Patch has been added to dev. Stack for catched exception only print to terminal when p2p log is on.
