### ISSUE TITLE
web3.eth.getUncle not working

### ISSUE THREAD

**Issue by jonathanjm** [aionnetwork/aion#127]
Error: Invalid JSON RPC response: undefined
    at Object.module.exports.InvalidResponse (/home/jonathan/aion/web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/home/jonathan/aion/web3/lib/web3/httpprovider.js:91:22)
    at RequestManager.send (/home/jonathan/aion/web3/lib/web3/requestmanager.js:58:32)
    at Eth.send [as getUncle] (/home/jonathan/aion/web3/lib/web3/method.js:145:58)
    at repl:1:10
    at REPLServer.defaultEval (repl.js:254:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:77:13)

**Comment by aion-jin** [comment]
Uncle not exist on aion main net.  
@ali-sharif    could you remove this func from aion_web3?

**Comment by jonathanjm** [comment]
Oh ok. Thanks.

**Comment by ali-sharif** [comment]
moving this ticket to aion_web3 repo
