### ISSUE TITLE
Throws NullPointer Exception

### ISSUE THREAD

**Issue by hbarclay** [aionnetwork/aion#13]
After running aion.sh for a few hours, an exception is thrown:

```
Exception in thread "process-in" java.lang.NullPointerException
    at org.aion.p2p.a0.P2pMgr.processInboundTcpNetRoute(P2pMgr.java:372)
    at org.aion.p2p.a0.P2pMgr.processInboundTcp(P2pMgr.java:481)
    at org.aion.p2p.a0.P2pMgr.lambda$runProcessInbound$3(P2pMgr.java:563)
    at java.base/java.lang.Thread.run(Unknown Source)
```

Ubuntu 16.04 in VirtualBox Version 5.1.18 r114002 (Qt5.6.2)

**Comment by JSorenSwanson** [comment]
I've also ran into this issue -- I'll try and reproduce it.

**Comment by aion-6368726973** [comment]
@hbarclay We have added patch for this and new binary will be released soon.
