### ISSUE TITLE
aion 0.14 kernal collapse 

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [aionnetwork/aion#164]
I have been run the core for several days. this afternoon, i just got the collapse 

```
18-03-11 11:56:52.910 ERROR SYNC [p2p-write]: <res-bodies invalid>
18-03-11 11:56:57.109 ERROR SYNC [p2p-write]: <res-bodies invalid>
18-03-11 12:42:49.334 INFO  SYNC [sync-import]: <import-best num=344562 hash=958dd0 txs=0>
18-03-11 12:42:51.209 ERROR SYNC [p2p-write]: <res-bodies invalid>
Exception in thread "BlkHdr" java.lang.NullPointerException
	at org.aion.txpool.common.AbstractTxPool.updateAccPoolState(Unknown Source)
	at org.aion.txpool.zero.TxPoolA0.remove(Unknown Source)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.clearPending(AionPendingStateImpl.java:472)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBestInternal(AionPendingStateImpl.java:426)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBest(AionPendingStateImpl.java:399)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:170)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:168)
	at org.aion.evtmgr.impl.handler.BlockHandler.dispatch(Unknown Source)
	at org.aion.evtmgr.impl.abs.AbstractHandler$1.run(Unknown Source)
Exception in thread "pow" java.lang.NullPointerException
	at org.aion.txpool.common.AbstractTxPool.updateAccPoolState(Unknown Source)
	at org.aion.txpool.common.AbstractTxPool.sortTxn(Unknown Source)
	at org.aion.txpool.zero.TxPoolA0.snapshot(Unknown Source)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.getPendingTransactions(AionPendingStateImpl.java:197)
	at org.aion.zero.impl.pow.AionPoW.createNewBlockTemplate(AionPoW.java:235)
	at org.aion.zero.impl.pow.AionPoW.lambda$init$0(AionPoW.java:113)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by AionJayT** [comment]
fixed
