### ISSUE TITLE
java.lang.InterruptedException at kernel shutdown

### ISSUE THREAD

**Issue by AlexandraRoatis** [aionnetwork/aion#173]
Kernel version: **0.1.15.8ff2b02**

```
18-03-13 14:40:46.591 INFO  GEN  [main]: loaded block <num=75456, root=bf10e72e... l=32>

   ============================================================== p2p-status-ac6f6a ==============================================================
   temp[  5] inbound[  0] outbound[  0] active[  0]                          s - seed node, td - total difficulty, # - block number, rv - revision


   ==================== ALL PEERS METRIC ===========================
   0 ID:c1f426 SEED:Y IP: 52.179.100.107 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   1 ID:0466a7 SEED:Y IP:191.232.176.213 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   2 ID:2da625 SEED:Y IP:   52.237.31.69 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   3 ID:f9ea8c SEED:Y IP: 52.231.206.150 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   4 ID:d9242b SEED:Y IP:   13.95.218.95 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  

18-03-13 14:40:46.666 INFO  GEN  [main]: <node-started endpoint=p2p://ac6f6aac-86ec-45ac-85b6-85c2f0486944@127.0.0.1:30303>
18-03-13 14:40:46.673 INFO  CONS [main]: <delayed-start-sealing>
18-03-13 14:40:46.684 DEBUG API  [main]: <account-manager init>
18-03-13 14:40:46.687 INFO  API  [main]: AionAPI Implementation Initiated
18-03-13 14:40:46.689 INFO  API  [zmq-api]: Starting Aion Api Server <port=8547>
18-03-13 14:40:46.692 DEBUG API  [main]: <rpc action=start bind=127.0.0.1:8545>
<p2p try-connect-52.237.31.69>
<p2p action=connect-outbound addr=52.237.31.69:30303 result=success>
<p2p read-msg-io-exception>
<p2p try-connect-52.179.100.107>
<p2p action=connect-outbound addr=52.179.100.107:30303 result=success>
<p2p read-msg-io-exception>
<p2p try-connect-191.232.176.213>
<p2p action=connect-outbound addr=191.232.176.213:30303 result=success>
<p2p read-msg-io-exception>
<p2p try-connect-52.231.206.150>
^C18-03-13 14:40:53.684 INFO  GEN  [Shutdown]: Starting shutdown process...
18-03-13 14:40:53.684 INFO  GEN  [Shutdown]: Shutting down zmq ProtocolProcessor
18-03-13 14:40:53.685 INFO  API  [Shutdown]: zmq-proxy thread shuting down...
18-03-13 14:40:53.685 INFO  API  [Shutdown]: waiting zmq-proxy thread shutdown
18-03-13 14:40:55.712 INFO  API  [zmq-api]: zmq-proxy thread was interrupted.
18-03-13 14:40:55.712 INFO  API  [zmq-api]: ProtocolProcessor.run thread finish.
18-03-13 14:40:55.712 INFO  API  [zmq-api]: Shutting down Sockets...
18-03-13 14:40:55.713 INFO  API  [pool-5-thread-1]: close callbackRun Sockets...
18-03-13 14:40:55.717 ERROR API  [pool-5-thread-10]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-13 14:40:55.717 ERROR API  [pool-5-thread-9]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-13 14:40:55.717 ERROR API  [pool-5-thread-4]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-13 14:40:55.717 ERROR API  [pool-5-thread-11]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-13 14:40:55.717 INFO  API  [pool-5-thread-9]: close workerRun Sockets...
18-03-13 14:40:55.717 ERROR API  [pool-5-thread-7]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-13 14:40:55.717 INFO  API  [pool-5-thread-4]: close workerRun Sockets...
18-03-13 14:40:55.717 INFO  API  [pool-5-thread-11]: close workerRun Sockets...
18-03-13 14:40:55.717 INFO  API  [pool-5-thread-7]: close workerRun Sockets...
18-03-13 14:40:55.717 ERROR API  [pool-5-thread-6]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-13 14:40:55.717 INFO  API  [pool-5-thread-6]: close workerRun Sockets...
18-03-13 14:40:55.717 ERROR API  [pool-5-thread-5]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-13 14:40:55.717 INFO  API  [pool-5-thread-10]: close workerRun Sockets...
18-03-13 14:40:55.717 INFO  API  [pool-5-thread-5]: close workerRun Sockets...
18-03-13 14:40:55.718 ERROR API  [pool-5-thread-8]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-13 14:40:55.718 INFO  API  [pool-5-thread-8]: close workerRun Sockets...

   ============================================================== p2p-status-ac6f6a ==============================================================
   temp[  5] inbound[  0] outbound[  3] active[  0]                          s - seed node, td - total difficulty, # - block number, rv - revision


   ==================== ALL PEERS METRIC ===========================
   0 ID:c1f426 SEED:Y IP: 52.179.100.107 PORT:30303 PORT_CONN:56066 FC:0 BB:       0  
   1 ID:0466a7 SEED:Y IP:191.232.176.213 PORT:30303 PORT_CONN:36812 FC:0 BB:       0  
   2 ID:2da625 SEED:Y IP:   52.237.31.69 PORT:30303 PORT_CONN:34640 FC:0 BB:       0  
   3 ID:f9ea8c SEED:Y IP: 52.231.206.150 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   4 ID:d9242b SEED:Y IP:   13.95.218.95 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  

18-03-13 14:40:56.678 INFO  CONS [Timer-0]: sealer starting 🔒 {2}
18-03-13 14:40:56.681 INFO  CONS [Timer-0]: sealer 1 starting.
18-03-13 14:40:56.681 INFO  CONS [Timer-0]: sealer 2 starting.
18-03-13 14:40:56.685 INFO  GEN  [Shutdown]: Shutdown zmq ProtocolProcessor... Done!
18-03-13 14:40:56.685 INFO  GEN  [Shutdown]: Shutting down sealer
18-03-13 14:40:56.685 INFO  CONS [Shutdown]: sealer stopping 🔒
18-03-13 14:40:56.685 INFO  CONS [Shutdown]: Interrupt sealer 1
18-03-13 14:40:56.685 INFO  CONS [Shutdown]: Interrupt sealer 2
18-03-13 14:40:56.686 INFO  CONS [Shutdown]: Stopped sealer 1
18-03-13 14:40:56.686 INFO  CONS [Shutdown]: Stopped sealer 2
18-03-13 14:40:56.686 INFO  GEN  [Shutdown]: Shutdown sealer... Done!
18-03-13 14:40:56.686 INFO  GEN  [Shutdown]: Shutting down the AionHub...
18-03-13 14:40:56.686 INFO  GEN  [Shutdown]: <KERNEL SHUTDOWN SEQUENCE>
18-03-13 14:40:56.686 INFO  GEN  [Shutdown]: <shutdown-sync-mgr>
<p2p-pi shutdown>
<p2p action=connect-outbound addr=52.231.206.150:30303 result=success>
18-03-13 14:40:56.689 INFO  GEN  [Shutdown]: <shutdown-p2p-mgr>
18-03-13 14:40:56.690 INFO  GEN  [Shutdown]: TransactionExecThread shutting down...
<p2p write-msg-io-exception node=f9ea8c>
java.lang.InterruptedException
18-03-13 14:40:56.690 INFO  GEN  [Shutdown]: TransactionExecThread waiting termination.
18-03-13 14:40:56.690 INFO  GEN  [Shutdown]: TransactionExecThread shutdown... Finished!
18-03-13 14:40:56.690 INFO  GEN  [Shutdown]: <shutdown-tx>
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1247)
.	at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317)
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:427)
	at org.aion.p2p.impl.TaskWrite.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
18-03-13 14:40:56.704 INFO  API  [pool-5-thread-3]: close eventRun Sockets...
18-03-13 14:40:56.704 INFO  API  [zmq-api]: Shutdown Sockets... Done!
...18-03-13 14:41:00.691 INFO  GEN  [Shutdown]: shutting down consensus...
18-03-13 14:41:00.692 INFO  GEN  [Shutdown]: shutdown consensus... Done!
18-03-13 14:41:00.692 INFO  GEN  [Shutdown]: shutting down DB...
18-03-13 14:41:00.693 INFO  GEN  [Shutdown]: details DB closed.
18-03-13 14:41:00.693 INFO  GEN  [Shutdown]: state DB closed.
18-03-13 14:41:00.694 INFO  GEN  [Shutdown]: transaction DB closed.
18-03-13 14:41:00.694 INFO  GEN  [Shutdown]: block DB closed.
18-03-13 14:41:00.694 INFO  GEN  [Shutdown]: shutdown DB... Done!
```

**Comment by AlexandraRoatis** [comment]
Occured again when stopping the kernel shortly after starting it.

```
18-03-14 11:57:25.789 INFO  GEN  [main]: loaded block <num=265585, root=ac3200a5... l=32>

   ============================================================== p2p-status-ac6f6a ==============================================================
   temp[  5] inbound[  0] outbound[  0] active[  0]                          s - seed node, td - total difficulty, # - block number, rv - revision


   ==================== ALL PEERS METRIC ===========================
   0 ID:c1f426 SEED:Y IP: 52.179.100.107 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   1 ID:0466a7 SEED:Y IP:191.232.176.213 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   2 ID:2da625 SEED:Y IP:   52.237.31.69 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   3 ID:f9ea8c SEED:Y IP: 52.231.206.150 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  
   4 ID:d9242b SEED:Y IP:   13.95.218.95 PORT:30303 PORT_CONN:   -1 FC:0 BB:       0  

18-03-14 11:57:25.866 INFO  GEN  [main]: <node-started endpoint=p2p://ac6f6aac-86ec-45ac-85b6-85c2f0486944@127.0.0.1:30303>
18-03-14 11:57:25.873 INFO  CONS [main]: <sealing-disabled>
<p2p try-connect-52.237.31.69>
<p2p action=connect-outbound addr=52.237.31.69:30303 result=success>
<p2p read-msg-io-exception>
^C18-03-14 11:57:27.977 INFO  GEN  [Shutdown]: Starting shutdown process...
18-03-14 11:57:27.978 INFO  GEN  [Shutdown]: Shutting down zmq ProtocolProcessor
18-03-14 11:57:28.915 ERROR API  [pool-5-thread-10]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-14 11:57:28.915 ERROR API  [pool-5-thread-11]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-14 11:57:28.915 ERROR API  [pool-5-thread-6]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-14 11:57:28.915 ERROR API  [pool-5-thread-5]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-14 11:57:28.915 ERROR API  [pool-5-thread-9]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-14 11:57:28.915 ERROR API  [pool-5-thread-8]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-14 11:57:28.915 ERROR API  [pool-5-thread-7]: ProtocolProcessor workerRun exception!! Context was terminated
18-03-14 11:57:28.915 ERROR API  [pool-5-thread-4]: ProtocolProcessor workerRun exception!! Context was terminated
<p2p try-connect-52.179.100.107>
<p2p action=connect-outbound addr=52.179.100.107:30303 result=success>
<p2p read-msg-io-exception>
<p2p try-connect-191.232.176.213>
18-03-14 11:57:30.978 INFO  GEN  [Shutdown]: Shutdown zmq ProtocolProcessor... Done!
18-03-14 11:57:30.978 INFO  GEN  [Shutdown]: Shutting down sealer
18-03-14 11:57:30.978 INFO  GEN  [Shutdown]: Shutdown sealer... Done!
18-03-14 11:57:30.978 INFO  GEN  [Shutdown]: Shutting down the AionHub...
18-03-14 11:57:30.978 INFO  GEN  [Shutdown]: <KERNEL SHUTDOWN SEQUENCE>
18-03-14 11:57:30.979 INFO  GEN  [Shutdown]: <shutdown-sync-mgr>
<p2p-pi shutdown>
<p2p action=connect-outbound addr=191.232.176.213:30303 result=success>
java.lang.InterruptedException
18-03-14 11:57:30.982 INFO  GEN  [Shutdown]: <shutdown-p2p-mgr>
18-03-14 11:57:30.982 INFO  GEN  [Shutdown]: TransactionExecThread shutting down...
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2037)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2114)
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
	at org.aion.p2p.impl.TaskWrite.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
18-03-14 11:57:30.983 INFO  GEN  [Shutdown]: TransactionExecThread waiting termination.
18-03-14 11:57:30.983 INFO  GEN  [Shutdown]: TransactionExecThread shutdown... Finished!
18-03-14 11:57:30.983 INFO  GEN  [Shutdown]: <shutdown-tx>
....18-03-14 11:57:34.984 INFO  GEN  [Shutdown]: shutting down consensus...
18-03-14 11:57:34.984 INFO  GEN  [Shutdown]: shutdown consensus... Done!
18-03-14 11:57:34.984 INFO  GEN  [Shutdown]: shutting down DB...
18-03-14 11:57:34.986 INFO  GEN  [Shutdown]: details DB closed.
18-03-14 11:57:34.987 INFO  GEN  [Shutdown]: state DB closed.
18-03-14 11:57:34.987 INFO  GEN  [Shutdown]: transaction DB closed.
18-03-14 11:57:34.987 INFO  GEN  [Shutdown]: block DB closed.
18-03-14 11:57:34.987 INFO  GEN  [Shutdown]: shutdown DB... Done!
```

**Comment by aion-6368726973** [comment]
Duplicated ticket as https://github.com/aionnetwork/aion/issues/117
