### ISSUE TITLE
Error after killing aion.sh

### ISSUE THREAD

**Issue by bajazid** [aionnetwork/aion#18]
Hi,

I killed aion.sh process and now I'm getting following error each time I start kernel:

```
18-02-14 21:09:42.685 ERROR DB   [main]: Failed to open the database LevelDB:<name=state,autocommit=ON,cache=OFF,compression=OFF> due to: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/xxxx/xxxx/aion/database/state/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:80)
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.open(AbstractDatabaseWithCache.java:179)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:236)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:174)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:77)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:44)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:63)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:68)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-14 21:09:42.922 ERROR DB   [main]: Failed to open the database LevelDB:<name=transaction,autocommit=ON,cache=OFF,compression=OFF> due to: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/xxxx/xxxx/aion/database/transaction/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:80)
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.open(AbstractDatabaseWithCache.java:179)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:236)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:178)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:77)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:44)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:63)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:68)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-14 21:09:42.930 ERROR DB   [main]: Failed to open the database LevelDB:<name=details,autocommit=ON,cache=OFF,compression=OFF> due to: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/xxxx/xxxx/aion/database/details/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:80)
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.open(AbstractDatabaseWithCache.java:179)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:236)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:182)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:77)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:44)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:63)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:68)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-14 21:09:42.940 ERROR DB   [main]: Failed to open the database LevelDB:<name=storage,autocommit=ON,cache=OFF,compression=OFF> due to: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/xxxx/xxxx/aion/database/storage/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:80)
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.open(AbstractDatabaseWithCache.java:179)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:236)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:186)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:77)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:44)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:63)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:68)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-14 21:09:42.949 ERROR DB   [main]: Failed to open the database LevelDB:<name=index,autocommit=ON,cache=OFF,compression=OFF> due to: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/xxxx/xxxx/aion/database/index/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:80)
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.open(AbstractDatabaseWithCache.java:179)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:236)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:190)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:77)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:44)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:63)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:68)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-14 21:09:43.053 ERROR DB   [main]: Failed to open the database LevelDB:<name=block,autocommit=ON,cache=OFF,compression=OFF> due to: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/xxxx/xxxx/aion/database/block/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:80)
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.open(AbstractDatabaseWithCache.java:179)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:236)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:194)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:77)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:44)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:63)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:68)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
Exception in thread "main" java.lang.RuntimeException: Database is not opened: LevelDBWithCache:<autocommit=OFF,size=UNBOUND,stats=OFF>
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.check(AbstractDatabaseWithCache.java:135)
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.get(AbstractDatabaseWithCache.java:466)
	at org.aion.dbmgr.driver.AbstractDatabaseWithCache.get(AbstractDatabaseWithCache.java:25)
	at org.aion.ds.DataSourceArray.size(DataSourceArray.java:82)
	at org.aion.db.a0.AionBlockStore.getMaxNumber(AionBlockStore.java:240)
	at org.aion.db.a0.AionBlockStore.getBestBlock(AionBlockStore.java:61)
	at org.aion.a0.AionHub.loadBlockchain(AionHub.java:204)
	at org.aion.a0.AionHub.<init>(AionHub.java:104)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-14 21:09:49.671 INFO  CONS [ConsHdr]: block sealed <num=150132, hash=cbcb4d, diff=16, tx=0>
18-02-14 21:10:03.296 INFO  CONS [ConsHdr]: block sealed <num=150133, hash=8540aa, diff=16, tx=0>
```
In addition pressing CTRL+C doesn't seems to be able to do clean shutdown after this. It just exits immediately.

**Comment by AlexandraRoatis** [comment]
The cause for this error is that one of the Aion instances has not been completely shut down yet and is still keeping the locks on the database.

Please run the following in a terminal:
```
ps -aux | grep java
```
Examine the output looking for processes like:
```
username  9883 [...] ./rt/bin/java -Xms2g --add-modules java.xml.bind -cp ./lib/* org.aion.Aion
```
Using the process numbers returned in the line above, kill each process running the Aion instance by typing:
```
kill 9883
```

Wait a few seconds for the process to terminate before starting a new instance. You can check that it was really terminated by executing again the command `ps -aux |  grep java`.

**Note:** For very "stubborn" processes you can call:
```
kill -9 9883
```
But typically the simple kill command should work.

**Comment by bajazid** [comment]
Yes, this really helped. Thank you @AlexandraRoatis
