### ISSUE TITLE
AionPoW calling closed database

### ISSUE THREAD

**Issue by AlexandraRoatis** [aionnetwork/aion#194]
Version **0.1.15.e247219**

Possible regression bug: AionPoW trying to access closed database 

Occurred multiple times when shutting down the kernel.

```
Exception in thread "pow" 18-03-15 12:23:15.801 INFO  GEN  [Shutdown]: transaction DB closed.
java.lang.RuntimeException: Database is not opened: LevelDBWithCache:<autocommit=OFF,size=UNBOUND,stats=ON>
	at org.aion.db.impl.AbstractDatabaseWithCache.check(Unknown Source)
	at org.aion.db.impl.AbstractDatabaseWithCache.get(Unknown Source)
	at org.aion.db.impl.AbstractDatabaseWithCache.get(Unknown Source)
	at org.aion.mcf.trie.JournalPruneDataSource.get(Unknown Source)
	at org.aion.mcf.trie.JournalPruneDataSource.get(Unknown Source)
	at org.aion.mcf.trie.Cache.get(Unknown Source)
	at org.aion.mcf.trie.TrieImpl.getNode(Unknown Source)
	at org.aion.mcf.trie.TrieImpl.get(Unknown Source)
	at org.aion.mcf.trie.TrieImpl.get(Unknown Source)
	at org.aion.mcf.trie.SecureTrie.get(Unknown Source)
	at org.aion.zero.impl.db.AionRepositoryImpl.getAccountState(AionRepositoryImpl.java:404)
	at org.aion.zero.impl.db.AionRepositoryImpl.loadAccountState(AionRepositoryImpl.java:430)
	at org.aion.mcf.db.AbstractRepositoryCache.getAccountState(Unknown Source)
	at org.aion.mcf.db.AbstractRepositoryCache.addBalance(Unknown Source)
	at org.aion.zero.impl.AionBlockchainImpl.addReward(AionBlockchainImpl.java:907)
	at org.aion.zero.impl.AionBlockchainImpl.generatePreBlock(AionBlockchainImpl.java:856)
	at org.aion.zero.impl.AionBlockchainImpl.createNewBlock(AionBlockchainImpl.java:515)
	at org.aion.zero.impl.pow.AionPoW.createNewBlockTemplate(AionPoW.java:237)
	at org.aion.zero.impl.pow.AionPoW.lambda$init$0(AionPoW.java:113)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by aion-6368726973** [comment]
ctrl-c
```
18-03-16 10:41:54.323 INFO  SYNC [sync-ib]: <import-best num=334219 hash=2e7354 txs=0>
18-03-16 10:41:54.389 INFO  SYNC [sync-ib]: <import-best num=334220 hash=b92b74 txs=0>
18-03-16 10:41:54.437 INFO  SYNC [sync-ib]: <import-best num=334221 hash=240a32 txs=0>
Exception in thread "pow" java.lang.RuntimeException: Database is not opened: LevelDBWithCache:<name=details,autocommit=OFF,size=UNBOUND,stats=OFF>
	at org.aion.db.impl.AbstractDatabaseWithCache.check(AbstractDatabaseWithCache.java:170)
	at org.aion.db.impl.AbstractDatabaseWithCache.get(AbstractDatabaseWithCache.java:520)
	at org.aion.db.impl.AbstractDatabaseWithCache.get(AbstractDatabaseWithCache.java:60)
	at org.aion.mcf.db.DetailsDataStore.get(DetailsDataStore.java:83)
	at org.aion.zero.impl.db.AionRepositoryImpl.getContractDetails(AionRepositoryImpl.java:381)
	at org.aion.zero.impl.db.AionRepositoryImpl.loadAccountState(AionRepositoryImpl.java:431)
	at org.aion.mcf.db.AbstractRepositoryCache.getAccountState(AbstractRepositoryCache.java:103)
	at org.aion.mcf.db.AbstractRepositoryCache.addBalance(AbstractRepositoryCache.java:208)
	at org.aion.zero.impl.AionBlockchainImpl.addReward(AionBlockchainImpl.java:907)
	at org.aion.zero.impl.AionBlockchainImpl.generatePreBlock(AionBlockchainImpl.java:856)
	at org.aion.zero.impl.AionBlockchainImpl.createNewBlock(AionBlockchainImpl.java:515)
	at org.aion.zero.impl.pow.AionPoW.createNewBlockTemplate(AionPoW.java:237)
	at org.aion.zero.impl.pow.AionPoW.lambda$init$0(AionPoW.java:113)
	at java.base/java.lang.Thread.run(Thread.java:844)

```
