### ISSUE TITLE
8G ram nodes will be killed when large transaction ( few thousands ) broadcast out.

### ISSUE THREAD

**Issue by aion-jin** [aionnetwork/aion#206]
![image](https://user-images.githubusercontent.com/35697444/37540623-09d55300-292e-11e8-845a-9cddff470115.png)

**Comment by alexander-vi** [comment]
Yes, that is my case.

18-03-19 10:54:55.553 INFO SYNC [sync-ib]: 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-5-thread-3"
Exception in thread “sync-gs” Exception in thread “p2p-pi” java.lang.OutOfMemoryError: Java heap space
at java.base/java.util.Arrays.copyOf(Arrays.java:3744)
at org.aion.p2p.impl.P2pMgr.read(Unknown Source)
at org.aion.p2p.impl.P2pMgr.access$300(Unknown Source)
at org.aion.p2p.impl.P2pMgr$TaskInbound.run(Unknown Source)
at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.OutOfMemoryError: Java heap space

How many memory should I have to avoid this? 16 gigs?

**Comment by AionJayT** [comment]
after v0.2.5 it won't have this issue. close issue.
