### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by yulongaion** [aionnetwork/aion#207]
```
Exception in thread "TxHdr" java.lang.UnsupportedOperationException
	at java.base/java.util.Collections$SingletonSet.removeIf(Collections.java:4792)
	at org.aion.zero.impl.blockchain.PendingTxCache.lambda$flush$2(PendingTxCache.java:186)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1604)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:591)
	at org.aion.zero.impl.blockchain.PendingTxCache.flush(PendingTxCache.java:168)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.flushCachePendingTx(AionPendingStateImpl.java:430)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$2.onPendingTxStateChange(AionPendingStateImpl.java:173)
	at org.aion.evtmgr.impl.handler.TxHandler.dispatch(TxHandler.java:57)
	at org.aion.evtmgr.impl.abs.AbstractHandler$1.run(AbstractHandler.java:66)
```

**Comment by yulongaion** [comment]
Doesn't seem to be fixed

```
Exception in thread "BlkHdr" java.lang.UnsupportedOperationException18-03-18 01:10:41.139 DEBUG SYNC [p2p-write]: <req-status from-node=f9ea8c>

	at java.base/java.util.Collections$1.remove(Collections.java:4701)
18-03-18 01:10:41.141 DEBUG SYNC [p2p-write]: <req-headers from-block=391723 take=512 from-node=555555>
	at org.aion.zero.impl.blockchain.PendingTxCache.lambda$flush$1(PendingTxCache.java:189)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1604)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:591)
	at org.aion.zero.impl.blockchain.PendingTxCache.flush(PendingTxCache.java:168)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.flushCachePendingTx(AionPendingStateImpl.java:420)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBest(AionPendingStateImpl.java:400)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:160)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:158)
	at org.aion.evtmgr.impl.handler.BlockHandler.dispatch(BlockHandler.java:63)
	at org.aion.evtmgr.impl.abs.AbstractHandler$1.run(AbstractHandler.java:66)
```

**Comment by yulongaion** [comment]
Fixed
