### ISSUE TITLE
eth.getBlock has stopped working

### ISSUE THREAD

**Issue by saaperezru** [aionnetwork/aion#23]
The eth.getBlock operation has stopped working in the web3 included in the aion-v0.1.11-2018-02-16.tar.bz2 version of the testnet binaries:

```
aion-127.0.0.1:8545> eth.getBlock(0)
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/home/ubuntu/aion/web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/home/ubuntu/aion/web3/lib/web3/httpprovider.js:91:22)
    at RequestManager.send (/home/ubuntu/aion/web3/lib/web3/requestmanager.js:58:32)
    at Eth.send [as getBlock] (/home/ubuntu/aion/web3/lib/web3/method.js:145:58)
```
It used to work fine in both versions 0.1.10 and 0.1.8.

I'm sorry if this is not the right place to report this, I was not sure about reporting this here or at aion_web3.

**Comment by aion-jin** [comment]
thanks saaperezru.  this is perfect place to report this. and initial thoughts from devs was missing node modules.   Chris will provide you more detail to fix this.

**Comment by jonathanjm** [comment]
Hi,
web3.eth.getBlockTransactionCount is not working either, will it be addressed here or should I create a separate issue for it?
