### ISSUE TITLE
dev branch & v0.1.16 latest build

### ISSUE THREAD

**Issue by aion-6368726973** [aionnetwork/aion#243]
java.lang.reflect.InvocationTargetException
```
18-03-20 19:03:10.625 ERROR GEN  [main]: Can not load the Event Manager Module
Exception in thread "main" java.lang.NullPointerException
	at org.aion.zero.impl.AionHub.loadEventMgr(AionHub.java:222)
	at org.aion.zero.impl.AionHub.<init>(AionHub.java:126)
	at org.aion.zero.impl.blockchain.AionImpl.<init>(AionImpl.java:77)
	at org.aion.zero.impl.blockchain.AionImpl.inst(AionImpl.java:70)
	at org.aion.zero.impl.blockchain.AionFactory.create(AionFactory.java:36)
	at org.aion.Aion.main(Unknown Source)
```

**Comment by AionJayT** [comment]
fixed in
0e8bb2007bdac94b969229cb563562616b2bb9f7
