### ISSUE TITLE
Two exceptions

### ISSUE THREAD

**Issue by yulongaion** [aionnetwork/aion#257]
```
Exception in thread "dump-threads-and-blocks" java.lang.NullPointerException
	at org.aion.zero.impl.db.AionBlockStore.dumpPastBlocks(AionBlockStore.java:574)
	at org.aion.utils.TaskDumpThreadsAndBlocks.run(TaskDumpThreadsAndBlocks.java:72)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

```
Exception in thread "sync-ib" java.lang.NullPointerException
	at org.aion.zero.impl.db.AionBlockStore.getChainBlockByNumber(AionBlockStore.java:193)
	at org.aion.zero.impl.db.AionBlockStore.getBestBlock(AionBlockStore.java:93)
	at org.aion.zero.impl.AionBlockchainImpl.isValid(AionBlockchainImpl.java:799)
	at org.aion.zero.impl.AionBlockchainImpl.add(AionBlockchainImpl.java:615)
	at org.aion.zero.impl.AionBlockchainImpl.add(AionBlockchainImpl.java:586)
	at org.aion.zero.impl.AionBlockchainImpl.tryToConnect(AionBlockchainImpl.java:485)
	at org.aion.zero.impl.sync.TaskImportBlocks.run(TaskImportBlocks.java:106)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by AionJayT** [comment]
Close the issue since not happen anymore after patch
