### ISSUE TITLE
NullPointerExceptions in updateAccPoolState

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion#299]
I got a whole bunch of the below NullPointerExceptions. The kernel just kept going though so had hundreds of them.

```
Exception in thread "ForkJoinPool-3-worker-28" java.lang.NullPointerException
	at org.aion.txpool.common.AbstractTxPool.updateAccPoolState(Unknown Source)
	at org.aion.txpool.zero.TxPoolA0.remove(Unknown Source)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.clearPending(AionPendingStateImpl.java:527)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBestInternal(AionPendingStateImpl.java:481)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBest(AionPendingStateImpl.java:424)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:161)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:159)
	at org.aion.evtmgr.impl.handler.BlockHandler.lambda$dispatch$0(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1409)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Exception in thread "ForkJoinPool-3-worker-10" java.lang.NullPointerException
	at org.aion.txpool.common.AbstractTxPool.updateAccPoolState(Unknown Source)
	at org.aion.txpool.zero.TxPoolA0.remove(Unknown Source)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.clearPending(AionPendingStateImpl.java:527)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBestInternal(AionPendingStateImpl.java:481)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBest(AionPendingStateImpl.java:424)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:161)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:159)
	at org.aion.evtmgr.impl.handler.BlockHandler.lambda$dispatch$0(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1409)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by JimVanEeden** [comment]
Not happening anymore on 0.2.x so closing.
