### ISSUE TITLE
Invalid block after transaction -> caused by running out of disk space

### ISSUE THREAD

**Issue by AlexandraRoatis** [aionnetwork/aion#311]
Once transactions come in blocks are considered invalid:
```
$ grep "IMPORTED_BEST" nohup.out | tail -1; grep "Invalid transaction: Tx nonce" nohup.out | head -1; grep "INVALID_BLOCK" nohup.out | head -1; 
18-03-29 17:51:17.582 INFO  SYNC [sync-ib]: <import-status: node = 7cefd6, number = 451274, txs = 333, result = IMPORTED_BEST, time elapsed = 397 ms>
18-03-29 17:51:17.681 WARN  CONS [sync-ib]: Invalid transaction: Tx nonce 1369514 != expected nonce 0 (parent nonce: 0): TransactionData [hash=ce8b89e4c31f263cae1b4e5cd339de3e59d9cf5ec682347ed3ee4ba1e7c32da2, nonce=1369514, receiveAddress=af580694107763cf6751c6771057517aeebba98a8cdb988ff3dd3ff0ae24653c, value=0, data=10462fd000000000000000000000000000000001, timeStamp=1522036228338250, Nrg=30000, NrgPrice=1, txType=1, sig=org.aion.crypto.ed25519.Ed25519Signature@60552ffc]
18-03-29 17:51:17.725 INFO  SYNC [sync-ib]: <import-status: node = 7cefd6, number = 451275, txs = 297, result = INVALID_BLOCK, time elapsed = 143 ms>
```
Relevant jstack output:
```
$ grep -n "17:51:17" consecutive-jstack-output.out 
139310:2018-03-29 17:51:17
```
[consecutive-jstack-output.tar.gz](https://github.com/aionnetwork/aion/files/1861395/consecutive-jstack-output.tar.gz)
[nohup.tar.gz](https://github.com/aionnetwork/aion/files/1861396/nohup.tar.gz)

**Comment by AlexandraRoatis** [comment]
Experienced again. Seems to be caused by running out of storage space.

```
18-04-06 09:29:01.084 ERROR DB   [sync-ib]: Unable to execute batch put/update operation on LevelDB:<name=storage,autocommit=ON,cache=ON,compression=ON>.
org.iq80.leveldb.DBException: IO error: /home/alexandra/AionWorkspace/dev_aion/database/storage/135857.log: No space left on device
	at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:153)
	at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:114)
	at org.aion.db.impl.leveldb.LevelDB.putBatch(Unknown Source)
	at org.aion.mcf.ds.XorDataSource.putBatch(Unknown Source)
	at org.aion.mcf.trie.Cache.setDB(Unknown Source)
	at org.aion.zero.db.AionContractDetailsImpl.decode(AionContractDetailsImpl.java:159)
	at org.aion.mcf.db.DetailsDataStore.syncLargeStorage(Unknown Source)
	at org.aion.zero.impl.db.AionRepositoryImpl.commitBlock(AionRepositoryImpl.java:465)
	at org.aion.zero.impl.AionBlockchainImpl.storeBlock(AionBlockchainImpl.java:993)
	at org.aion.zero.impl.AionBlockchainImpl.add(AionBlockchainImpl.java18-04-06 09:29:01.372 ERROR CONS [sync-ib]: Attempting to add INVALID block.
18-04-06 09:29:04.910 INFO  SYNC [sync-ib]: <import-status: node = UBER8b, number = 523719, txs = 427, result = NO_PARENT, time elapsed = 14 ms>
18-04-06 09:29:04.928 INFO  SYNC [sync-ib]: <import-status: node = UBER8b, number = 523720, txs = 533, result = NO_PARENT, time elapsed = 18 ms>
18-04-06 09:29:04.961 INFO  SYNC [sync-ib]: <import-status: node = UBER8b, number = 523721, txs = 389, result = NO_PARENT, time elapsed = 33 ms>
18-04-06 09:29:04.983 INFO  SYNC [sync-ib]: <import-status: node = UBER8b, number = 523722, txs = 425, result = NO_PARENT, time elapsed = 22 ms>
[sync-status avg-import=0.82 b/s td=588436538/598805313 b-num=523699/526763 b-hash=624eb474ff387c5f34a9b9d997124308f53ffe7615792ede00d08f595e09cf6d/3d643039e5b0e98a2c9eb99028599dd1dbc1fc963b30d5f2699f09ff6df429af]

================================================================== p2p-status-roa66a ==================================================================
temp[ 23] inbound[  0] outbound[  3] active[  8]                            s - seed node, td - total difficulty, # - block number, bv - binary version

          s               td          #                                                             hash              ip  port     conn              bv
-------------------------------------------------------------------------------------------------------------------------------------------------------
id:UBER8b          598805313     526763 3d643039e5b0e98a2c9eb99028599dd1dbc1fc963b30d5f2699f09ff6df429af   52.151.57.138 30304 outbound  0.1.19.5fef797
id:c1f426 y        598805244     526762 70e8cff09a129a00ec98d00586b7a58ab73e64f715f86cbb7bc23711660a5374  52.179.100.107 30303 outbound  0.1.19.5fef797
id:0466a7 y        598802024     526762 70e8cff09a129a00ec98d00586b7a58ab73e64f715f86cbb7bc23711660a5374 191.232.176.213 30303 outbound  0.1.18.d68881b
id:2da625 y        598802024     526762 70e8cff09a129a00ec98d00586b7a58ab73e64f715f86cbb7bc23711660a5374    52.237.31.69 30303 outbound         unknown
id:d9242b y        598802024     526762 70e8cff09a129a00ec98d00586b7a58ab73e64f715f86cbb7bc23711660a5374    13.95.218.95 30303 outbound         unknown
id:22225a y        594442150     525460 f92a86c786958c8afaacfb969d887a932af12fc8f8dfebef5c05550f6595e779   70.31.126.252 30303 outbound         unknown
id:f9ea8c y        591461108     524634 a980cd7509661ca6fb7370d11ea302e5d3b2ff7bfa336c69564831a8627a6a40  52.231.206.150 30303 outbound         unknown
id:92c250                  0          0                                                                    212.47.253.30 30303 outbound  0.1.19.5fef797


18-04-06 09:29:06.570 WARN  CONS [sync-ib]: Invalid transaction: Tx nonce 12295403 != expected nonce 12295969 (parent nonce: 12295969): TransactionData [hash=c633145439d98f2360e551ba674ed223adab7a891b4a928b7c1e77695eb680b9, nonce=12295403, receiveAddress=df6b66f5beb0fe5ea62946e306ffcf09e645fcf28662f7a4ca9755b1675b9bc5, value=0, data=10462fd000000000000000000000000000000001, timeStamp=1522988850274495, Nrg=21400, NrgPrice=1, txType=1, sig=org.aion.crypto.ed25519.Ed25519Signature@5fc18cae]
18-04-06 09:29:06.570 ERROR CONS [sync-ib]: Attempting to add INVALID block.
18-04-06 09:29:06.570 INFO  SYNC [sync-ib]: <import-status: node = 0466a7, number = 523700, txs = 566, result = INVALID_BLOCK, time elapsed = 44 ms>
18-04-06 09:29:06.572 INFO  SYNC [sync-ib]: <import-status: node = 0466a7, number = 523701, txs = 566, result = NO_PARENT, time elapsed = 2 ms>
18-04-06 09:29:06.576 INFO  SYNC [sync-ib]: <import-status: node = 0466a7, number = 523702, txs = 566, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:29:06.579 INFO  SYNC [sync-ib]: <import-status: node = 0466a7, number = 523703, txs = 566, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:29:06.582 INFO  SYNC [sync-ib]: <import-status: node = 0466a7, number = 523704, txs = 566, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:29:06.587 INFO  SYNC [sync-ib]: <import-status: node = 0466a7, number = 523705, txs = 567,18-04-06 09:29:06.858 ERROR CONS [sync-ib]: Attempting to add INVALID block.
receive handshake. nid:1704595784

















18-04-06 09:30:30.878 WARN  CONS [sync-ib]: Invalid transaction: Tx nonce 12295403 != expected nonce 12295969 (parent nonce: 12295969): TransactionData [hash=c633145439d98f2360e551ba674ed223adab7a891b4a928b7c1e77695eb680b9, nonce=12295403, receiveAddress=df6b66f5beb0fe5ea62946e306ffcf09e645fcf28662f7a4ca9755b1675b9bc5, value=0, data=10462fd000000000000000000000000000000001, timeStamp=1522988850274495, Nrg=21400, NrgPrice=1, txType=1, sig=org.aion.crypto.ed25519.Ed25519Signature@6efa3248]
18-04-06 09:30:30.878 ERROR CONS [sync-ib]: Attempting to add INVALID block.
18-04-06 09:30:30.878 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523700, txs = 566, result = INVALID_BLOCK, time elapsed = 37 ms>
18-04-06 09:30:30.880 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523701, txs = 566, result = NO_PARENT, time elapsed = 2 ms>
18-04-06 09:30:30.883 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523702, txs = 566, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:30:30.886 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523703, txs = 566, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:30:30.889 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523704, txs = 566, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:30:30.894 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523705, txs = 567, result = NO_PARENT, time elapsed = 5 ms>
18-04-06 09:30:30.895 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523706, txs = 567, result = NO_PARENT, time elapsed = 1 ms>
18-04-06 09:30:30.898 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523707, txs = 567, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:30:30.902 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523708, txs = 567, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:30:30.904 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523709, txs = 568, result = NO_PARENT, time elapsed = 2 ms>
18-04-06 09:30:30.907 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523710, txs = 568, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:30:30.911 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523711, txs = 570, result = NO_PARENT, time elapsed = 4 ms>
18-04-06 09:30:30.913 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523712, txs = 568, result = NO_PARENT, time elapsed = 2 ms>
18-04-06 09:30:30.915 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523713, txs = 569, result = NO_PARENT, time elapsed = 2 ms>
18-04-06 09:30:30.917 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523714, txs = 570, result = NO_PARENT, time elapsed = 2 ms>
18-04-06 09:30:30.921 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523715, txs = 152, result = NO_PARENT, time elapsed = 4 ms>
18-04-06 09:30:30.925 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523716, txs = 570, result = NO_PARENT, time elapsed = 4 ms>
18-04-06 09:30:30.930 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523717, txs = 491, result = NO_PARENT, time elapsed = 5 ms>
18-04-06 09:30:30.934 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523718, txs = 571, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:30:30.936 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523719, txs = 427, result = NO_PARENT, time elapsed = 2 ms>
18-04-06 09:30:30.938 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523720, txs = 533, result = NO_PARENT, time elapsed = 2 ms>
18-04-06 09:30:30.941 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523721, txs = 389, result = NO_PARENT, time elapsed = 3 ms>
18-04-06 09:30:30.945 INFO  SYNC [sync-ib]: <import-status: node = 22225a, number = 523722, txs = 425, result = NO_PARENT, time elapsed = 4 ms>
18-04-06 09:30:31.120 WARN  CONS [sync-ib]: Invalid transaction: Tx nonce 12295403 != expected nonce 12295969 (parent nonce: 12295969): TransactionData [hash=c633145439d98f2360e551ba674ed223adab7a891b4a928b7c1e77695eb680b9, nonce=12295403, receiveAddress=df6b66f5beb0fe5ea62946e306ffcf09e645fcf28662f7a4ca9755b1675b9bc5, value=0, data=10462fd000000000000000000000000000000001, timeStamp=1522988850274495, Nrg=21400, NrgPrice=1, txType=1, sig=org.aion.crypto.ed25519.Ed25519Signature@7b3ac0f5]
```

**Comment by AlexandraRoatis** [comment]
TODO: call shutdown on "No space left on device" errors
