### ISSUE TITLE
Sync attempting to import very old block

### ISSUE THREAD

**Issue by AlexandraRoatis** [aionnetwork/aion#347]
Version 0.1.18.c3ac56f

_The missing trie state error below is due to the state database having been pruned and can be ignored._

The issue is that there is no reason to import a block so far behind as `304363` when the current best block is `515616` and the sync config is:
```
	<sync>
		<blocks-backward-max>16</blocks-backward-max>
		<blocks-import-max>32</blocks-import-max>
		<blocks-queue-max>48</blocks-queue-max>
		<show-status>true</show-status>
	</sync>
```

```
[sync-status avg-import=4.39 b/s td=570539208/570534702 b-num=515616/515613 b-hash=a40f6d918b5d111acf04921363360ed3873078db0bfc173a6ceb8a29c02fe85d/50b4a91c56e28f06180f7c073975cf57f92abf7decb953881bff3a3e58c80b7c]

================================================================== p2p-status-Alexa3 ==================================================================
temp[ 14] inbound[  0] outbound[  0] active[  5]                            s - seed node, td - total difficulty, # - block number, bv - binary version

          s               td          #                                                             hash              ip  port     conn              bv
-------------------------------------------------------------------------------------------------------------------------------------------------------
id:555555          570536957     515615 949abe05fbd9dac40735352924e1b34a14d083c164748e1971ab9479cff29acb  66.207.217.190 30303  inbound          0.1.18
id:d9242b y        570536957     515615 949abe05fbd9dac40735352924e1b34a14d083c164748e1971ab9479cff29acb    13.95.218.95 30303 outbound  0.1.18.2f7a044
id:ef96c3          570534702     515614 2387edcb83c98525f4c025b7327b7d03dc247ea4aae50f5ca06b8301ea954960  66.207.217.190 30303 outbound  0.1.18.6d271fd
id:ffc26a                  0          0                                                                    52.233.40.169 30303 outbound  0.1.18.434ddd1
id:068843                  0          0                                                                    188.24.77.189 30305  inbound  0.1.18.42be2c7


18-04-05 00:58:51.156 ERROR CONS [p2p-worker-12]: Unexpected error: 
java.lang.RuntimeException: Invalid Trie state, missing node 9450b1a47d66695f3b7743c8aff8272dad978ed6a27947f0c4f637c63e3101a9
	at org.aion.mcf.trie.TrieImpl.insert(Unknown Source)
	at org.aion.mcf.trie.TrieImpl.insertOrDelete(Unknown Source)
	at org.aion.mcf.trie.TrieImpl.update(Unknown Source)
	at org.aion.mcf.trie.SecureTrie.update(Unknown Source)
	at org.aion.zero.impl.db.AionRepositoryImpl.updateAccountState(AionRepositoryImpl.java:335)
	at org.aion.zero.impl.db.AionRepositoryImpl.updateBatch(AionRepositoryImpl.java:152)
	at org.aion.zero.db.AionRepositoryCache.flush(AionRepositoryCache.java:96)
	at org.aion.zero.impl.AionBlockchainImpl.addReward(AionBlockchainImpl.java:965)
	at org.aion.zero.impl.AionBlockchainImpl.applyBlock(AionBlockchainImpl.java:939)
	at org.aion.zero.impl.AionBlockchainImpl.processBlock(AionBlockchainImpl.java:870)
	at org.aion.zero.impl.AionBlockchainImpl.add(AionBlockchainImpl.java:652)
	at org.aion.zero.impl.AionBlockchainImpl.add(AionBlockchainImpl.java:609)
	at org.aion.zero.impl.AionBlockchainImpl.tryConnectAndFork(AionBlockchainImpl.java:435)
	at org.aion.zero.impl.AionBlockchainImpl.tryToConnect(AionBlockchainImpl.java:507)
	at org.aion.zero.impl.AionBlockchainImpl.tryToConnect(AionBlockchainImpl.java:99)
	at org.aion.zero.impl.sync.handler.BlockPropagationHandler.processIncomingBlock(BlockPropagationHandler.java:166)
	at org.aion.zero.impl.sync.handler.BroadcastNewBlockHandler.receive(BroadcastNewBlockHandler.java:86)
	at org.aion.p2p.impl1.P2pMgr.lambda$handleKernelMsg$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
18-04-05 00:58:51.163 INFO  SYNC [p2p-worker-12]: <import-status: node = ffc26a, number = 304363, txs = 0, result = INVALID_BLOCK, time elapsed = 155 ms>
18-04-05 00:58:51.819 INFO  CONS [p2p-worker-7]: branching: from = 304362/367238ee34f9d93288cdd490bb97d224a0fcc92d3389dac15f502236d0530b72, to = 515617/ec253c620968b67298c146c514c6a31483dbab56c52c950951cf3dcc3cdde02f
18-04-05 00:58:51.820 INFO  CONS [p2p-worker-7]: branching: common block = 515616/a40f6d918b5d111acf04921363360ed3873078db0bfc173a6ceb8a29c02fe85d
18-04-05 00:58:51.821 INFO  SYNC [p2p-worker-7]: <import-status: node = ef96c3, number = 515617, txs = 0, result = IMPORTED_BEST, time elapsed = 480 ms>
```

**Comment by AlexandraRoatis** [comment]
should be mitigated by the added heuristic approach #353
