### ISSUE TITLE
web3.net.peerCount not working

### ISSUE THREAD

**Issue by jonathanjm** [aionnetwork/aion#35]
Error: Invalid JSON RPC response: undefined
    at Object.module.exports.InvalidResponse (/var/www/aionstats/node_modules/aion-web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/var/www/aionstats/node_modules/aion-web3/lib/web3/httpprovider.js:91:22)
    at RequestManager.send (/var/www/aionstats/node_modules/aion-web3/lib/web3/requestmanager.js:58:32)
    at get [as peerCount] (/var/www/aionstats/node_modules/aion-web3/lib/web3/property.js:107:62)
    at Object.<anonymous> (/var/www/aionstats/routes/index.js:9:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

same thing is happening with the web3.version.* methods

**Comment by ali-sharif** [comment]
missing some web3 0.2.x functions:
 
web3 base: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3js-api-reference
geth management extensions: https://github.com/ethereum/go-ethereum/wiki/Management-APIs#list-of-management-apis

**Comment by gonuco** [comment]
@ali-sharif     could you list all funcs we need integration ?

**Comment by ali-sharif** [comment]
I'll open a separate ticket for Web3 api enhancement, with a list of potential features we can add. 

By my determination, our current implementation covers all the critical-path functions that (heuristically) get used 95% of the time these days.

**Comment by ali-sharif** [comment]
resolved in PR https://github.com/aionnetwork/aion/pull/141
