### ISSUE TITLE
"dump-threads-and-blocks" Error 

### ISSUE THREAD

**Issue by aion-anakha** [aionnetwork/aion#350]
```
                     _____                  
      .'.       |  .~     ~.  |..          |
    .'   `.     | |         | |  ``..      |
  .''''''''`.   | |         | |      ``..  |
.'           `. |  `._____.'  |          ``|

                    NETWORK  v0.1.18.2474cb8


18-04-05 18:13:05.064 DEBUG TXPOOL [main]: TxPoolA0.updateBlkNrgLimit nrg[15000000] blkNrgLimit[15000000]
18-04-05 18:13:05.094 INFO  GEN  [main]: loaded block <num=513533, root=ac36fbbc... l=32>
[sync-status avg-import=0.00 b/s td=564934269/0 b-num=513533/0 b-hash=06225e609b5a0ef04da064ac63f3135a7fafe4fd3a0c557ebf3ee52d801137c0/]

================================================================== p2p-status-f77dbf ==================================================================
temp[  5] inbound[  0] outbound[  0] active[  0]                            s - seed node, td - total difficulty, # - block number, bv - binary version


Exception in thread "dump-threads-and-blocks" java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
        at org.aion.utils.ThreadDumper.dumpThreadInfo(ThreadDumper.java:36)
        at org.aion.utils.TaskDumpThreadsAndBlocks.run(TaskDumpThreadsAndBlocks.java:65)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: java.lang.management.ManagementFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 3 more
18-04-05 18:13:05.181 INFO  GEN  [main]: <node-started endpoint=p2p://f77dbf73-2718-400e-a6d2-9f6d0b8c2d5a@0.0.0.0:30303>
18-04-05 18:13:05.189 INFO  CONS [main]: <sealing-disabled>
[sync-status avg-import=0.00 b/s td=564934269/0 b-num=513533/0 b-hash=06225e609b5a0ef04da064ac63f3135a7fafe4fd3a0c557ebf3ee52d801137c0/]

================================================================== p2p-status-f77dbf ==================================================================
temp[ 11] inbound[  0] outbound[  0] active[  1]                            s - seed node, td - total difficulty, # - block number, bv - binary version

          s               td          #                                                             hash              ip  port     conn              bv
-------------------------------------------------------------------------------------------------------------------------------------------------------
id:2da625 y        470447889     489476 e1a4459db0906772b00cd38c4a82f2221d151908849e161c0a9c710f697d664d    52.237.31.69 30303 outbound  0.1.18.d358e66
```

**Comment by AlexandraRoatis** [comment]
the dump threads and blocks functionality was removed since no longer used
