### ISSUE TITLE
NullPointer on inbound p2p thread

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion#356]
~~~~java
18-04-06 04:59:50.808 DEBUG SYNC [p2p-worker-4]: <req-status node=0466a7>
Exception in thread "p2p-worker-4" java.lang.NullPointerException
        at org.aion.p2p.impl.comm.NodeMgr.updateAllNodesInfo(Unknown Source)
        at org.aion.zero.impl.sync.handler.ResStatusHandler.receive(ResStatusHandler.java:82)
        at org.aion.p2p.impl1.P2pMgr$TaskReceive.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:844)

~~~~

**Comment by JimVanEeden** [comment]
+1

this is followed by **a lot** of:

```
<drop node: 5fc13f>
<drop node: 5fc13f>
<drop node: 5fc13f>
...
```

**Comment by JimVanEeden** [comment]
Once synced the drop node thing doesn't pop up anymore, but it does cause the peers not to be updated anymore. So they all seem stuck on the same block and no new ones are imported for me either.
