### ISSUE TITLE
RPC Server Connection Issue

### ISSUE THREAD

**Issue by Nytingale** [aionnetwork/aion#369]
When the RPC flag is set to active, an IllegalArgumentException is immediately thrown:

Exception in thread "main" java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1332)
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1255)
	at org.aion.api.server.rpc.RpcProcessor.<init>(Unknown Source)
	at org.aion.api.server.http.HttpServer.<init>(Unknown Source)
	at org.aion.Aion.main(Unknown Source)

**Comment by JayT106** [comment]
fixed in https://github.com/aionnetwork/aion/pull/380

**Comment by AionJayT** [comment]
fixed in https://github.com/aionnetwork/aion/pull/380
