### ISSUE TITLE
new version 0.2 heap dump

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [aionnetwork/aion#378]
running about 13 hours...

```

java.lang.OutOfMemoryError: Java heap space
Dumping heap to ./heapdump.hprof ...
Heap dump file created [1773013339 bytes in 17,880 secs]
Exception in thread "p2p-tcp" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:68)
	at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:341)
	at org.aion.p2p.impl1.ChannelBuffer.<init>(Unknown Source)
	at org.aion.p2p.impl1.P2pMgr$TaskConnectPeers.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)

```

**Comment by aion-6368726973** [comment]
@Xiaoyang-Zhu Can provide head dump file ?

**Comment by Xiaoyang-Zhu** [comment]
sure, but i just found the size of the "heapdump.hprof" file is about 1.8GB...do you wanna me send it to you?

**Comment by aion-6368726973** [comment]
@Xiaoyang-Zhu issue reproduced and on patching.

**Comment by Xiaoyang-Zhu** [comment]
Glad to hear that
