### ISSUE TITLE
Inbound Thread Liveness

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion#384]
~~~~
18-04-12 04:38:41.203 DEBUG SYNC [p2p-worker-6]: <res-status best-block=538593 node=a51215>
[sync-status avg-import=0.09 b/s td=701428349/701426141 b-num=565068/565064 b-hash=65d3724345992d1e81058fe394256b192f9d664d22e91dd247f32b9ff7cd1de3/27ac9f43635ce9e10a2752f7cfb351cf79026de40f35b99da5a91cbae38e24c2]
<p2p try-connect-66.207.217.190>
<p2p read-msg-null-exception>
<p2p close-socket->
Exception in thread "p2p-in" java.lang.NullPointerException
        at org.aion.p2p.impl1.P2pMgr$TaskInbound.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:844)

~~~~

Inbound thread for ``T1`` died due to this, I suspect the root cause is us trying to close a SelectionKey that is null because the selector no longer has a key registered with the channel. I suspect this is possible if the channel throws a NPE before it was ever registered with the selector (perhaps on ``accept``?)

**Comment by AionJayT** [comment]
this issue has been solved. close the issue
