### ISSUE TITLE
ClassCastException when starting AION

### ISSUE THREAD

**Issue by romaion** [aionnetwork/aion#404]
S2R:
1. Run org.aion.Aion
2. Observe:
Exception in thread "pow" java.lang.ClassCastException: org.aion.rlp.RLPList cannot be cast to org.aion.rlp.RLPItem
	at org.aion.zero.db.AionContractDetailsImpl.decode(AionContractDetailsImpl.java:120)
	at org.aion.mcf.db.DetailsDataStore.get(DetailsDataStore.java:95)
	at org.aion.zero.impl.db.AionRepositoryImpl.getContractDetails(AionRepositoryImpl.java:392)
	at org.aion.zero.impl.db.AionRepositoryImpl.loadAccountState(AionRepositoryImpl.java:453)
	at org.aion.mcf.db.AbstractRepositoryCache.loadAccountState(AbstractRepositoryCache.java:227)
	at org.aion.mcf.db.AbstractRepositoryCache.getAccountState(AbstractRepositoryCache.java:110)
	at org.aion.mcf.db.AbstractRepositoryCache.addBalance(AbstractRepositoryCache.java:283)
	at org.aion.zero.impl.AionBlockchainImpl.addReward(AionBlockchainImpl.java:1047)
	at org.aion.zero.impl.AionBlockchainImpl.generatePreBlock(AionBlockchainImpl.java:992)
	at org.aion.zero.impl.AionBlockchainImpl.createNewBlockInternal(AionBlockchainImpl.java:657)
	at org.aion.zero.impl.AionBlockchainImpl.createNewBlock(AionBlockchainImpl.java:613)
	at org.aion.zero.impl.pow.AionPoW.createNewBlockTemplate(AionPoW.java:273)
	at org.aion.zero.impl.pow.AionPoW.lambda$init$0(AionPoW.java:151)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by AlexandraRoatis** [comment]
The same database folder was used with different incompatible changes. The storage model after the #388 optimization is not compatible with the storage model before it.
