### ISSUE TITLE
p2p issue java.lang.IllegalStateException

### ISSUE THREAD

**Issue by AionMiner** [aionnetwork/aion#562]
> I'm running:
>
> - **Which Aion version?**: v0.2.8.ef5df39c
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

Running the kernel with 30303/tcp open, my node serves 40+ peers. I've recently noticed after several hours I start getting repeated [p2p-in] notices from the seed nodes and then `java.lang.IllegalStateException` starts occuring:

```
18-07-25 14:21:26.038 INFO  P2P  [p2p-in]: new-connection 191.232.164.119:35458
18-07-25 14:21:27.466 INFO  SYNC [sync-ib]: <import-status: node = 1187ac, sync mode = NORMAL, hash = e8e2a1, number = 757424, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:21:31.448 INFO  SYNC [p2p-worker-2]: <import-status: node = 0aa3e3, hash = e3bf27, number = 757425, txs = 0, result = IMPORTED_BEST, time elapsed = 1 ms>
18-07-25 14:21:34.805 INFO  SYNC [sync-ib]: <import-status: node = bd0a0c, sync mode = NORMAL, hash = e3bf27, number = 757425, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:21:41.758 INFO  SYNC [p2p-worker-2]: <import-status: node = a84149, hash = d8858a, number = 757426, txs = 1, result = IMPORTED_BEST, time elapsed = 1 ms>
18-07-25 14:21:45.285 INFO  SYNC [sync-ib]: <import-status: node = 72edb3, sync mode = NORMAL, hash = d8858a, number = 757426, txs = 1, result = EXIST, time elapsed = 0 ms>
18-07-25 14:21:49.982 INFO  P2P  [p2p-in]: new-connection 13.92.155.115:55016
18-07-25 14:21:57.229 INFO  SYNC [p2p-worker-0]: <import-status: node = c33d22, hash = 24d6d9, number = 757427, txs = 4, result = IMPORTED_BEST, time elapsed = 1 ms>
18-07-25 14:22:00.276 INFO  SYNC [sync-ib]: <import-status: node = c33d10, sync mode = NORMAL, hash = 24d6d9, number = 757427, txs = 4, result = EXIST, time elapsed = 0 ms>
18-07-25 14:22:00.587 INFO  SYNC [p2p-worker-3]: <import-status: node = c33d30, hash = 9338ca, number = 757428, txs = 0, result = IMPORTED_BEST, time elapsed = 0 ms>
18-07-25 14:22:01.709 INFO  SYNC [p2p-worker-0]: <import-status: node = a84149, hash = e9f4c1, number = 757429, txs = 0, result = IMPORTED_BEST, time elapsed = 0 ms>
18-07-25 14:22:03.650 INFO  P2P  [p2p-in]: new-connection 191.232.164.119:35554
18-07-25 14:22:06.233 INFO  SYNC [sync-ib]: <import-status: node = c33d30, sync mode = NORMAL, hash = 9338ca, number = 757428, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:22:06.233 INFO  SYNC [sync-ib]: <import-status: node = c33d30, sync mode = NORMAL, hash = e9f4c1, number = 757429, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:22:12.761 INFO  SYNC [p2p-worker-0]: <import-status: node = c33d30, hash = e51a13, number = 757430, txs = 0, result = IMPORTED_BEST, time elapsed = 1 ms>
18-07-25 14:22:13.768 INFO  SYNC [p2p-worker-1]: <import-status: node = a684f4, hash = 5d0f38, number = 757431, txs = 1, result = IMPORTED_BEST, time elapsed = 1 ms>
18-07-25 14:22:19.967 INFO  P2P  [p2p-in]: new-connection 13.92.155.115:55132
18-07-25 14:22:20.111 INFO  SYNC [sync-ib]: <import-status: node = 05c9dd, sync mode = NORMAL, hash = e51a13, number = 757430, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:22:20.111 INFO  SYNC [sync-ib]: <import-status: node = 05c9dd, sync mode = NORMAL, hash = 5d0f38, number = 757431, txs = 1, result = EXIST, time elapsed = 0 ms>
18-07-25 14:22:22.851 INFO  SYNC [p2p-worker-2]: <import-status: node = e6184a, hash = b9f69c, number = 757432, txs = 0, result = IMPORTED_BEST, time elapsed = 1 ms>
java.lang.IllegalStateException
        at java.base/java.util.concurrent.ConcurrentHashMap$BaseIterator.remove(ConcurrentHashMap.java:3456)
        at org.aion.p2p.impl.comm.NodeMgr.timeoutActive(Unknown Source)
        at org.aion.p2p.impl.comm.NodeMgr.timeoutCheck(Unknown Source)
        at org.aion.p2p.impl1.tasks.TaskClear.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:844)
18-07-25 14:22:23.777 ERROR P2P  [p2p-clear]: TaskClear exception null
18-07-25 14:22:26.909 INFO  SYNC [sync-ib]: <import-status: node = 949f79, sync mode = NORMAL, hash = b9f69c, number = 757432, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:22:29.286 INFO  SYNC [p2p-worker-1]: <import-status: node = e6184a, hash = 147e4d, number = 757433, txs = 0, result = IMPORTED_BEST, time elapsed = 0 ms>
18-07-25 14:22:31.769 INFO  SYNC [sync-ib]: <import-status: node = 2663e2, sync mode = NORMAL, hash = 147e4d, number = 757433, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:22:35.321 INFO  SYNC [p2p-worker-2]: <import-status: node = c33d10, hash = 5ef8f3, number = 757434, txs = 0, result = IMPORTED_BEST, time elapsed = 1 ms>
18-07-25 14:22:36.293 INFO  P2P  [p2p-in]: new-connection 191.232.164.119:35638
18-07-25 14:22:38.109 INFO  SYNC [sync-ib]: <import-status: node = 55ef1e, sync mode = NORMAL, hash = 5ef8f3, number = 757434, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:22:55.127 INFO  P2P  [p2p-in]: new-connection 13.92.155.115:55230
18-07-25 14:22:55.130 INFO  SYNC [p2p-worker-1]: <import-status: node = a84149, hash = a2b72a, number = 757435, txs = 0, result = IMPORTED_BEST, time elapsed = 2 ms>
18-07-25 14:22:55.135 INFO  SYNC [p2p-worker-2]: <import-status: node = a84149, hash = 64d274, number = 757436, txs = 0, result = IMPORTED_BEST, time elapsed = 6 ms>
18-07-25 14:22:56.117 INFO  SYNC [p2p-worker-3]: <import-status: node = ab477e, hash = a39105, number = 757437, txs = 0, result = IMPORTED_BEST, time elapsed = 0 ms>
18-07-25 14:23:00.308 INFO  SYNC [p2p-worker-0]: <import-status: node = a84149, hash = 88800e, number = 757438, txs = 1, result = IMPORTED_BEST, time elapsed = 1 ms>
18-07-25 14:23:03.183 INFO  P2P  [p2p-in]: new-connection 135.0.87.68:58342
18-07-25 14:23:04.449 INFO  SYNC [sync-ib]: <import-status: node = 7d1ef1, sync mode = NORMAL, hash = a2b72a, number = 757435, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:23:04.449 INFO  SYNC [sync-ib]: <import-status: node = 7d1ef1, sync mode = NORMAL, hash = 64d274, number = 757436, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:23:04.450 INFO  SYNC [sync-ib]: <import-status: node = 7d1ef1, sync mode = NORMAL, hash = a39105, number = 757437, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:23:07.806 INFO  SYNC [p2p-worker-1]: <import-status: node = bd0a0c, hash = 8b9b2b, number = 757439, txs = 0, result = IMPORTED_BEST, time elapsed = 1 ms>
18-07-25 14:23:09.676 INFO  P2P  [p2p-in]: new-connection 191.232.164.119:35728
18-07-25 14:23:09.677 INFO  SYNC [sync-ib]: <import-status: node = bd0a0c, sync mode = NORMAL, hash = 88800e, number = 757438, txs = 1, result = EXIST, time elapsed = 0 ms>
18-07-25 14:23:10.898 INFO  SYNC [sync-ib]: <import-status: node = 05c9dd, sync mode = NORMAL, hash = 8b9b2b, number = 757439, txs = 0, result = EXIST, time elapsed = 0 ms>
18-07-25 14:23:14.882 INFO  SYNC [p2p-worker-2]: <import-status: node = a84149, hash = 87a890, number = 757440, txs = 1, result = IMPORTED_BEST, time elapsed = 0 ms>
18-07-25 14:23:18.763 INFO  SYNC [sync-ib]: <import-status: node = a684f4, sync mode = NORMAL, hash = 87a890, number = 757440, txs = 1, result = EXIST, time elapsed = 0 ms>
18-07-25 14:23:21.153 INFO  P2P  [p2p-in]: new-connection 13.92.155.115:55358
18-07-25 14:23:45.124 INFO  P2P  [p2p-in]: new-connection 191.232.164.119:35828
18-07-25 14:23:55.734 INFO  P2P  [p2p-in]: new-connection 13.92.155.115:55486
```

This cycle then repeats every ~20-30 minutes, unless I restart of the kernel. When I do restart I do not see the mass [p2p-in] from the seed nodes nor the IllegalStateException for several hours. 

Note, I am also running aion-solo-pool-0.2.2 on the same machine. My block notification via RPC polling seems to lag behind when this occurs too and thus new work is delayed/not issued.

If I stop port forwarding 30303 then I only remain connected to the 7 seed nodes, but neither issue occurs.

**Comment by aion-chris** [comment]
```
if (now - node.getTimestamp() > timeout) {
    ...
    it.remove();    
}       
if (!node.getChannel().isConnected()) {
    ...
    it.remove();
}     
```
IllegalStateException throws at remove() twice

**Comment by AionJayT** [comment]
Thanks for report. we aware this issue and will patch in the next release.
Please see this link.
#539
