### ISSUE TITLE
Concurrency issues in SpecialLockedDatabase

### ISSUE THREAD

**Issue by a312516552** [aionnetwork/aion#577]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Aion version?**: 0.2.x.{git-revision}
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04
> - **How installed?**:  from source
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
#
All read/write methods in SpecialLockedDatabase require read lock instead of write lock. So the lock  actually doesn't take effect since every thread can have read lock in a situation without write lock. This database failed in my multi-thread test case listed below.

----------------------Testcase-------------------

package org.aion.db.impl;

import org.aion.base.db.IByteArrayKeyValueDatabase;
import org.aion.db.generic.SpecialLockedDatabase;
import java.util.Random;
import org.aion.db.impl.leveldb.LevelDBConstants;
import org.junit.Test;
import java.io.File;
import java.util.Properties;
import static org.aion.db.impl.DatabaseFactory.Props;
import static org.junit.Assert.*;

/**
 * author: Aedan
 */
public class SpecialLockedDatabaseTest {

    String dbPath = new File(System.getProperty("user.dir"), "tmp").getAbsolutePath();
    String dbVendor = DBVendor.LEVELDB.toValue();
    public String dbName = "test";
    private SpecialLockedDatabase specialLockedDatabase;

    void generateDatabase() {
        Properties props = new Properties();
        props.setProperty(Props.DB_TYPE, dbVendor);
        props.setProperty(Props.DB_NAME, dbName);
        props.setProperty(Props.DB_PATH, dbPath);
        props.setProperty(Props.BLOCK_SIZE, String.valueOf(LevelDBConstants.BLOCK_SIZE));
        props.setProperty(Props.MAX_FD_ALLOC, String.valueOf(LevelDBConstants.MAX_OPEN_FILES));
        props.setProperty(Props.WRITE_BUFFER_SIZE, String.valueOf(LevelDBConstants.WRITE_BUFFER_SIZE));
        props.setProperty(Props.DB_CACHE_SIZE, String.valueOf(LevelDBConstants.CACHE_SIZE));
        IByteArrayKeyValueDatabase db = DatabaseFactory.connect(props);
        assertNotNull(db);
        specialLockedDatabase = new SpecialLockedDatabase(db);
    }

    @Test
    public void specialLockedDatabaseConcurrencyTest() {
        generateDatabase();
        specialLockedDatabase.open();

        TestThread testThread_1 = new TestThread();
        Thread thread_1 = new Thread(testThread_1);
        TestThread testThread_2 = new TestThread();
        Thread thread_2 = new Thread(testThread_2);
        TestThread testThread_3 = new TestThread();
        Thread thread_3 = new Thread(testThread_3);
        TestThread testThread_4 = new TestThread();
        Thread thread_4 = new Thread(testThread_4);

        thread_1.start();
        thread_2.start();
        thread_3.start();
        thread_4.start();
        try{
            Thread.sleep(10000);
        } catch (Exception e){
            e.printStackTrace();
        }
    }

    class TestThread implements Runnable {

        @Override
        public void run() {
            Random random = new Random();

            for (int i = 1; i <= 10; i++) {
                byte[] key = intToBytes(i);
                byte[] value = intToBytes(random.nextInt());
                byte[] result;

                specialLockedDatabase.put(key, value);
                System.out.println("Thread" + this.toString() + " puts " + bytesToInt(key) + "  " + bytesToInt(value));

                result = specialLockedDatabase.get(key).get();
                System.out.println("Thread" + this.toString() + " gets " + bytesToInt(key) + "  " + bytesToInt(result));

                assertArrayEquals(value, result);
            }
        }

        byte[] intToBytes(int intData) {
            byte[] bytes = new byte[4];
            bytes[0] = (byte) (intData & 0xff);
            bytes[1] = (byte) ((intData >> 8) & 0xff);
            bytes[2] = (byte) ((intData >> 16) & 0xff);
            bytes[3] = (byte) ((intData >> 24) & 0xff);
            return bytes;
        }

        int bytesToInt(byte[] b) {
            return   b[3] & 0xFF | (b[2] & 0xFF) << 8 | (b[1] & 0xFF) << 16 | (b[0] & 0xFF) << 24;
        }
    }

}

-------------------------result1-----------------
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 16777216  -2085687747
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@777d6039 puts 16777216  -128402536
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@24ca1285 puts 16777216  -946639271
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@15593ed4 puts 16777216  1269384981
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 16777216  -2085687747
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@24ca1285 gets 16777216  -2085687747
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@777d6039 gets 16777216  -2085687747
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@15593ed4 gets 16777216  -2085687747
Exception in thread "Thread-1" arrays first differed at element [0]; expected:<-57> but was:<-125>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:341)
	at org.junit.Assert.assertArrayEquals(Assert.java:352)
	at org.aion.db.impl.SpecialLockedDatabaseTest$TestThread.run(SpecialLockedDatabaseTest.java:80)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.AssertionError: expected:<-57> but was:<-125>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 5 more
Exception in thread "Thread-3" arrays first differed at element [0]; expected:<75> but was:<-125>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:341)
	at org.junit.Assert.assertArrayEquals(Assert.java:352)
	at org.aion.db.impl.SpecialLockedDatabaseTest$TestThread.run(SpecialLockedDatabaseTest.java:80)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.AssertionError: expected:<75> but was:<-125>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 5 more
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 33554432  1104843349
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 33554432  1104843349
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 50331648  -187434307
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 50331648  -187434307
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 67108864  320313431
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 67108864  320313431
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 83886080  -227290847
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 83886080  -227290847
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 100663296  -939340937
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 100663296  -939340937
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 117440512  274591045
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 117440512  274591045
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 134217728  335979463
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 134217728  335979463
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 150994944  -1882284843
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 150994944  -1882284843
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 puts 167772160  -1493584747
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@2024f245 gets 167772160  -1493584747
Exception in thread "Thread-2" arrays first differed at element [0]; expected:<-8> but was:<-125>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:341)
	at org.junit.Assert.assertArrayEquals(Assert.java:352)
	at org.aion.db.impl.SpecialLockedDatabaseTest$TestThread.run(SpecialLockedDatabaseTest.java:80)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.AssertionError: expected:<-8> but was:<-125>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 5 more

-------------------------result2-----------------

Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@540c0f1c puts 16777216  24263225
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@540c0f1c gets 16777216  -672124731
Exception in thread "Thread-1" arrays first differed at element [0]; expected:<1> but was:<-41>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:341)
	at org.junit.Assert.assertArrayEquals(Assert.java:352)
	at org.aion.db.impl.SpecialLockedDatabaseTest$TestThread.run(SpecialLockedDatabaseTest.java:80)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.AssertionError: expected:<1> but was:<-41>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 5 more
Exception in thread "Thread-0" arrays first differed at element [0]; expected:<-60> but was:<-41>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:341)
	at org.junit.Assert.assertArrayEquals(Assert.java:352)
	at org.aion.db.impl.SpecialLockedDatabaseTest$TestThread.run(SpecialLockedDatabaseTest.java:80)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.AssertionError: expected:<-60> but was:<-41>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 5 more
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 16777216  -672124731
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@28b5e345 puts 16777216  -994422466
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 16777216  -672124731
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@28b5e345 gets 16777216  -672124731
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 33554432  -344855254
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 33554432  -344855254
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 50331648  -1759735576
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 50331648  -1759735576
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 67108864  -1857239777
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 67108864  -1857239777
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 83886080  1901223960
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 83886080  1901223960
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@42c103a puts 16777216  -516089126
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@42c103a gets 16777216  -672124731
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 100663296  1133660140
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 100663296  1133660140
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 117440512  214972318
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 117440512  214972318
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 134217728  -1063580598
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 134217728  -1063580598
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 150994944  642714494
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 150994944  642714494
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 puts 167772160  1634241166
Threadorg.aion.db.impl.SpecialLockedDatabaseTest$TestThread@33221ee4 gets 167772160  1634241166
Exception in thread "Thread-2" arrays first differed at element [0]; expected:<-31> but was:<-41>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:341)
	at org.junit.Assert.assertArrayEquals(Assert.java:352)
	at org.aion.db.impl.SpecialLockedDatabaseTest$TestThread.run(SpecialLockedDatabaseTest.java:80)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.AssertionError: expected:<-31> but was:<-41>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 5 more

**Comment by AionJayT** [comment]
Hi @a312516552, do you have the git revision for your testcase?

**Comment by AlexandraRoatis** [comment]
This class is an optimization for implementations that are already synchronized and do not require the write locks. Note that it is only used with LevelDB and RocksDB. The other implementations use the `LockedDatabase` class as you can see in the `DatabaseFactory#connectWithLocks` method. You can run our `ConcurrencyTest` unit tests to verify that the functionality is correct. You will note that the unit tests are run with every database configuration that can be used by the blockchain.
