### ISSUE TITLE
 Address already in use error

### ISSUE THREAD

**Issue by 43061b4a** [aionnetwork/aion#6]
```
./aion.sh
18-02-05 19:07:06.242 INFO  GEN  [main]: DB is empty - adding Genesis
18-02-05 19:07:06.282 INFO  GEN  [main]: loaded genesis block <num=0, root=de51d2fd692eadf87271316e2adbb84dd89012261a7442fb6cd62bcc2ed03c77>
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.aion.p2p.a0.P2pMgr.run(P2pMgr.java:862)
	at org.aion.a0.AionHub.<init>(AionHub.java:129)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
```
Setting up AION first time and getting this error. This does not specify the port that's already in use.

**Update:**
```
<p2p>
			<ip>127.0.0.1</ip>
			<port>3030[X]</port>
			<discover>false</discover>
			<show-status>false</show-status>
</p2p>
```
Chaging port to 3030[X] (X:0-9) fixed the error.

**Comment by aion-Ross** [comment]
An error like this usually means another application was already bound to port 30303 - only a single application can be bound to a port at a time. 

Changing the port like you did in the update will solve those types of issues.

**Comment by 43061b4a** [comment]
I knew what the error was but error message didn't list the port that was in use. I had to go in config files. It'd be nice if error message shows it.
