### ISSUE TITLE
<error on-write-config-xml-to-file>

### ISSUE THREAD

**Issue by smile201708** [aionnetwork/aion#669]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Aion version?**: v0.3.1.dcaf9e8-2018-08-30
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04
> - **How installed?**: via binaries / aion-v0.3.1.dcaf9e8-2018-08-30.tar.bz2
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**: no

I use tar xvjf aion-v0.3.1.dcaf9e8-2018-08-30.tar.bz2 
then cd aion
./aion.sh
first return 
Config Override
javax.xml.stream.XMLStreamException: Underlying stream encoding 'ASCII' and input paramter for writeStartDocument() method 'utf-8' do not match.
	at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.verifyEncoding(XMLStreamWriterImpl.java:1246)
	at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeStartDocument(XMLStreamWriterImpl.java:1184)
	at java.xml/com.sun.xml.internal.stream.writers.XMLStreamWriterImpl.writeStartDocument(XMLStreamWriterImpl.java:1167)
	at org.aion.zero.impl.config.CfgAion.toXML(Unknown Source)
	at org.aion.Aion.main(Unknown Source)
<error on-write-config-xml-to-file>

so I retry ./aion.sh
return

<error on-parsing-config-xml msg=ParseError at [row,col]:[1,1]
Message: Premature end of file.>

What should I do next?

**Comment by AcharyaOne** [comment]
Hi, how did you solve this problem?
