### ISSUE TITLE
node console.js

### ISSUE THREAD

**Issue by phpergithub** [aionnetwork/aion#671]
node console.js
module.js:328
    throw err;
    ^

Error: Cannot find module 'bignumber.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/aion/web3/lib/utils/utils.js:37:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by satran004** [comment]
Have you tried  ‘ npm install ‘ before running this?
