### ISSUE TITLE
node somehow get stuck when using web3 getBalance call

### ISSUE THREAD

**Issue by AionJayT** [aionnetwork/aion#752]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Aion version?**: 0.2.x.{git-revision}
0.3.2.059b63c5 with mainnet
> - **Which operating system?**: Linux
> - **Which distributor and version?**: Ubuntu 16.04 under VM
> - **How installed?**: from source
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes, then issue was gone.

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
tried this command:
```
web3.eth.getBalance("0xa08091ab0325e384Ac45E560d2F85E4B741363aa98881D52d54233A02b33FCaa").then(console.log);
```
then the web3 didn't get response and see kernel has the null message.

java.lang.Throwable: null
    at java.base@11.0.1/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
    at java.base@11.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:1009)
    at java.base@11.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1324)
    at java.base@11.0.1/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738)
    at app//org.aion.zero.impl.db.AionRepositoryImpl.getSnapshotTo(AionRepositoryImpl.java:572)
    at app//org.aion.api.server.rpc.ApiWeb3Aion.getRepoByJsonBlockId(ApiWeb3Aion.java:2845)
    at app//org.aion.api.server.rpc.ApiWeb3Aion.eth_getBalance(ApiWeb3Aion.java:434)
    at app//org.aion.api.server.rpc.RpcMethods.lambda$new$5(RpcMethods.java:154)
    at app//org.aion.api.server.rpc.RpcMethods$$Lambda$83/0x0000000800201840.call(Unknown Source)
    at app//org.aion.api.server.rpc.RpcProcessor.processObject(RpcProcessor.java:124)
    at app//org.aion.api.server.rpc.RpcProcessor.handleSingle(RpcProcessor.java:197)
    at app//org.aion.api.server.rpc.RpcProcessor.process(RpcProcessor.java:70)
    at app//org.aion.api.server.http.undertow.AionUndertowRpcHandler.lambda$handleRequest$0(AionUndertowRpcHandler.java:83)

**Comment by qoire** [comment]
Hey, I was not able to reproduce this consistently on my local node. Is this reproducable? For the record my node is not synced up.
