### ISSUE TITLE
ConcurrentModificationException - BlkHdr

### ISSUE THREAD

**Issue by aion-anakha** [aionnetwork/aion#81]
Occurred when running transaction generator.

```
Exception in thread "BlkHdr" java.util.ConcurrentModificationException
        at org.apache.commons.collections4.map.AbstractLinkedMap$LinkIterator.nextEntry(AbstractLinkedMap.java:552)
        at org.apache.commons.collections4.map.AbstractLinkedMap$EntrySetIterator.next(AbstractLinkedMap.java:415)
        at org.apache.commons.collections4.map.AbstractLinkedMap$EntrySetIterator.next(AbstractLinkedMap.java:407)
        at org.aion.zero.impl.blockchain.NonceMgr.flush(NonceMgr.java:137)
        at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBest(AionPendingStateImpl.java:416)
        at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:174)
        at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:172)
        at org.aion.evtmgr.impl.handler.BlockHandler.dispatch(Unknown Source)
        at org.aion.evtmgr.impl.abs.AbstractHandler$1.run(Unknown Source)
```

**Comment by yulongaion** [comment]
Needs to synchronize the map when iterating its elements

**Comment by JayT106** [comment]
might fix in this commit
https://github.com/aionnetwork/aion/pull/96

**Comment by aion-anakha** [comment]
Still seeing it when I run the txn-generator, running transactions with the Java API 
```
java.util.ConcurrentModificationException
	at org.apache.commons.collections4.map.AbstractLinkedMap$LinkIterator.nextEntry(AbstractLinkedMap.java:552)
	at org.apache.commons.collections4.map.AbstractLinkedMap$EntrySetIterator.next(AbstractLinkedMap.java:415)
	at org.apache.commons.collections4.map.AbstractLinkedMap$EntrySetIterator.next(AbstractLinkedMap.java:407)
	at org.aion.zero.impl.blockchain.NonceMgr.flush(NonceMgr.java:136)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl.processBest(AionPendingStateImpl.java:412)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:170)
	at org.aion.zero.impl.blockchain.AionPendingStateImpl$1.onBest(AionPendingStateImpl.java:168)
	at org.aion.evtmgr.impl.handler.BlockHandler.dispatch(Unknown Source)
	at org.aion.evtmgr.impl.abs.AbstractHandler$1.run(Unknown Source)
```

**Comment by ali-sharif** [comment]
Still an issue.  Seeing it when multiple transactions from different accounts get sealed into the same block, modEvtMgr throws concurrent modification exception (need to use thread-safe map).

**Comment by AionJayT** [comment]
fixed in
https://github.com/aionnetwork/aion/pull/172
