### ISSUE TITLE
Failed to initialize DB

### ISSUE THREAD

**Issue by mpunisher** [aionnetwork/aion#9]
I was running the kernel normally until I get this problem 

> 18-02-08 19:05:23.427 ERROR DB   [main]: Failed to initialize DB: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/med/aion/database/state/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:94)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:229)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:154)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:73)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:46)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:59)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:64)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-08 19:05:23.643 ERROR DB   [main]: Failed to initialize DB: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/med/aion/database/transaction/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:94)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:229)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:157)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:73)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:46)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:59)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:64)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-08 19:05:23.645 ERROR DB   [main]: Failed to initialize DB: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/med/aion/database/details/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:94)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:229)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:160)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:73)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:46)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:59)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:64)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-08 19:05:23.647 ERROR DB   [main]: Failed to initialize DB: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/med/aion/database/storage/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:94)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:229)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:163)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:73)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:46)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:59)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:64)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-08 19:05:23.649 ERROR DB   [main]: Failed to initialize DB: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/med/aion/database/index/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:94)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:229)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:166)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:73)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:46)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:59)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:64)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-08 19:05:23.758 ERROR DB   [main]: Failed to initialize DB: 
org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: lock /home/med/aion/database/block/LOCK: Resource temporarily unavailable
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at org.aion.dbmgr.driver.leveldb.LevelDB.open(LevelDB.java:94)
	at org.aion.db.AbstractRepository.connectAndOpen(AbstractRepository.java:229)
	at org.aion.db.AbstractRepository.initializeDatabasesAndCaches(AbstractRepository.java:169)
	at org.aion.db.a0.AionRepositoryImpl.init(AionRepositoryImpl.java:73)
	at org.aion.db.a0.AionRepositoryImpl.<init>(AionRepositoryImpl.java:46)
	at org.aion.db.a0.AionRepositoryImpl$AionRepositoryImplHolder.<clinit>(AionRepositoryImpl.java:59)
	at org.aion.db.a0.AionRepositoryImpl.inst(AionRepositoryImpl.java:64)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:164)
	at org.aion.a0.AionBlockchainImpl.<init>(AionBlockchainImpl.java:80)
	at org.aion.a0.AionBlockchainImpl$Holder.<clinit>(AionBlockchainImpl.java:212)
	at org.aion.a0.AionBlockchainImpl.inst(AionBlockchainImpl.java:216)
	at org.aion.a0.AionHub.<init>(AionHub.java:91)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)
18-02-08 19:05:24.328 INFO  GEN  [main]: DB is empty - adding Genesis
18-02-08 19:05:24.420 INFO  GEN  [main]: loaded genesis block <num=0, root=de51d2fd692eadf87271316e2adbb84dd89012261a7442fb6cd62bcc2ed03c77>
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at org.aion.p2p.a0.P2pMgr.run(P2pMgr.java:862)
	at org.aion.a0.AionHub.<init>(AionHub.java:129)
	at org.aion.blockchain.AionImpl.<init>(AionImpl.java:53)
	at org.aion.blockchain.AionImpl.inst(AionImpl.java:46)
	at org.aion.blockchain.AionFactory.create(AionFactory.java:12)
	at org.aion.Aion.main(Aion.java:65)

**Comment by AlexandraRoatis** [comment]
Are you trying to run two instances with the same configuration? Or did you have problems shutting down an instance? Based on the error message above, it looks like there are multiple threads trying to access the same resources.

**Comment by AlexandraRoatis** [comment]
If you still have the terminal open you can do `Ctrl+C` to shut down the instance.
If the process is running in the background, open a new terminal and execute the following command:
```
ps -fu | grep java
```
If it displays a process like `java -jar aion.jar`, kill that process.

**Comment by mpunisher** [comment]
thanks. But now I have another problem , the kernel frozen like this

18-02-09 16:38:21.143 INFO  GEN  [main]: loaded block <num=122812, root=c7f74ffc... l=32>
18-02-09 16:38:21.237 INFO  GEN  [main]: <node-started endpoint=p2p://u8EIm4AZ-Xtky-tBJv-NsON-NsONzTDpIHrr@127.0.0.1:30303>
18-02-09 16:38:21.241 INFO  CONS [main]: <delayed-start-sealing>
18-02-09 16:38:31.294 INFO  CONS [Timer-0]: sealer starting 🔒 {2}
18-02-09 16:38:31.299 INFO  CONS [Timer-0]: sealer 1 starting.
18-02-09 16:38:31.299 INFO  CONS [Timer-0]: sealer 2 starting.

**Comment by AlexandraRoatis** [comment]
I suspect your node is finding it difficult to choose the main chain. 
You can edit the `config.xml` file to allow the kernel to display more information by updating `<SYNC>DEBUG</SYNC>`.
Also, you can try to temporarily remove one or several of the seed nodes.
For example remove `<node>p2p://za365d12-af7f-4775-91b7-938e57e7f7b9@52.228.26.125:30303</node>` and give it some time to find the main chain.

**Comment by mpunisher** [comment]
can you take a look I keep getting "import-unsuccess"
```

18-02-09 18:33:25.154 DEBUG SYNC [process-in]: <res-blocks-headers from-block=122684 to-block=123004 size=321 from-node=1542405440>
18-02-09 18:33:26.230 DEBUG SYNC [process-in]: <incoming-headers size=321 from=122684 to=123004 imported-headers=321>
18-02-09 18:33:27.807 DEBUG SYNC [sync-headers]: <send-get-headers from-node=1542405440 from=122684 to=123004 self-best=122812 remote-best=127104>
18-02-09 18:33:29.161 DEBUG SYNC [process-in]: <res-blocks-headers from-block=122684 to-block=123004 size=321 from-node=1542405440>
18-02-09 18:33:30.161 DEBUG SYNC [process-in]: <incoming-headers size=321 from=122684 to=123004 imported-headers=321>
18-02-09 18:33:31.808 DEBUG SYNC [sync-headers]: <send-get-headers from-node=-1610192319 from=122684 to=123004 self-best=122812 remote-best=132392>
18-02-09 18:33:35.808 DEBUG SYNC [sync-headers]: <send-get-headers from-node=-1610192319 from=122684 to=123004 self-best=122812 remote-best=132392>
18-02-09 18:33:39.433 DEBUG SYNC [process-in]: <res-status best-block=132392 from-node=-1610192319>
18-02-09 18:33:39.433 DEBUG SYNC [process-in]: <network-best-block-updated num=132392 self-num=122812 continue-on-sync>
18-02-09 18:33:39.809 DEBUG SYNC [sync-headers]: <send-get-headers from-node=-1610192319 from=122684 to=123004 self-best=122812 remote-best=132392>
18-02-09 18:33:43.810 DEBUG SYNC [sync-headers]: <send-get-headers from-node=-1610192319 from=122684 to=123004 self-best=122812 remote-best=132392>
18-02-09 18:33:47.810 DEBUG SYNC [sync-headers]: <send-get-headers from-node=-1610192319 from=122684 to=123004 self-best=122812 remote-best=132392>
18-02-09 18:33:50.123 DEBUG SYNC [process-in]: <res-status best-block=127104 from-node=1542405440>
18-02-09 18:33:50.123 DEBUG SYNC [process-in]: <network-best-block-updated num=127104 self-num=122812 continue-on-sync>
18-02-09 18:33:51.811 DEBUG SYNC [sync-headers]: <send-get-headers from-node=1542405440 from=122684 to=123004 self-best=122812 remote-best=127104>
18-02-09 18:33:53.144 DEBUG SYNC [process-in]: <res-blocks-headers from-block=122684 to-block=123004 size=321 from-node=1542405440>
18-02-09 18:33:54.088 DEBUG SYNC [process-in]: <incoming-headers size=321 from=122684 to=123004 imported-headers=321>
18-02-09 18:33:55.811 DEBUG SYNC [sync-headers]: <send-get-headers from-node=1542405440 from=122684 to=123004 self-best=122812 remote-best=127104>
18-02-09 18:33:57.256 DEBUG SYNC [process-in]: <res-blocks-headers from-block=122684 to-block=123004 size=321 from-node=-1610192319>
18-02-09 18:33:58.266 DEBUG SYNC [process-in]: <incoming-headers size=321 from=122684 to=123004 imported-headers=321>
18-02-09 18:33:58.267 DEBUG SYNC [process-in]: <res-blocks-headers from-block=122684 to-block=123004 size=321 from-node=1542405440>
18-02-09 18:33:59.230 DEBUG SYNC [sync-blocks]: <req-blocks from=122684 take=321>
18-02-09 18:33:59.316 DEBUG SYNC [process-in]: <incoming-headers size=321 from=122684 to=123004 imported-headers=321>
18-02-09 18:33:59.316 DEBUG SYNC [process-in]: <res-status best-block=127104 from-node=1542405440>
18-02-09 18:33:59.316 DEBUG SYNC [process-in]: <network-best-block-updated num=127104 self-num=122812 continue-on-sync>
18-02-09 18:33:59.316 DEBUG SYNC [process-in]: <req-status from-node=1542405440>
18-02-09 18:33:59.814 DEBUG SYNC [sync-headers]: <send-get-headers from-node=1542405440 from=122684 to=123004 self-best=122812 remote-best=127104>
18-02-09 18:33:59.861 DEBUG SYNC [process-in]: <req-status from-node=1542405440>
18-02-09 18:34:01.130 DEBUG SYNC [process-in]: <res-blocks-headers from-block=122684 to-block=123004 size=321 from-node=1542405440>
18-02-09 18:34:02.216 DEBUG SYNC [process-in]: <incoming-headers size=321 from=122684 to=123004 imported-headers=321>
18-02-09 18:34:03.815 DEBUG SYNC [sync-headers]: <send-get-headers from-node=-1610192319 from=122684 to=123004 self-best=122812 remote-best=132392>
18-02-09 18:34:07.815 DEBUG SYNC [sync-headers]: <send-get-headers from-node=-1610192319 from=122684 to=123004 self-best=122812 remote-best=132392>
18-02-09 18:34:08.129 DEBUG SYNC [process-in]: <res-status best-block=127104 from-node=1542405440>
18-02-09 18:34:08.129 DEBUG SYNC [process-in]: <network-best-block-updated num=127104 self-num=122812 continue-on-sync>
18-02-09 18:34:11.152 DEBUG SYNC [process-in]: <res-status best-block=127104 from-node=1542405440>
18-02-09 18:34:11.152 DEBUG SYNC [process-in]: <network-best-block-updated num=127104 self-num=122812 continue-on-sync>
18-02-09 18:34:11.492 DEBUG SYNC [process-in]: <res-blocks-bodies bodies=321 from-node=-1610192319>
18-02-09 18:34:11.492 DEBUG SYNC [process-in]: <validate-incoming-blocks size=321 from=122684 to=123004>
18-02-09 18:34:11.492 DEBUG SYNC [sync-import]: <try-import-block num=122684 hash=f70c7c parent=1dde5a>
18-02-09 18:34:11.492 DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=122684 hash=f70c7c>
18-02-09 18:34:11.492 DEBUG SYNC [sync-import]: <try-import-block num=122685 hash=1aafcc parent=f70c7c>
18-02-09 18:34:11.492 DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=122685 hash=1aafcc>
18-02-09 18:34:11.492 DEBUG SYNC [sync-import]: <try-import-block num=122686 hash=ccec4a parent=1aafcc>
18-02-09 18:34:11.492 DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=122686 hash=ccec4a>
18-02-09 18:34:11.492 DEBUG SYNC [sync-import]: <try-import-block num=122687 hash=8a50e3 parent=ccec4a>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=122687 hash=8a50e3>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <try-import-block num=122688 hash=cec239 parent=8a50e3>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=122688 hash=cec239>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <try-import-block num=122689 hash=125bae parent=cec239>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=122689 hash=125bae>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <try-import-block num=122690 hash=aa5cdc parent=125bae>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=122690 hash=aa5cdc>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <try-import-block num=122691 hash=920aea parent=aa5cdc>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <import-unsuccess err=no-parent num=122691 hash=920aea>
18-02-09 18:34:11.493 DEBUG SYNC [sync-import]: <try-import-block num=122692 hash=c036f6 parent=920aea>

```

**Comment by AlexandraRoatis** [comment]
Unfortunately, the only solution at this point is to delete the database and start the sync again.
I added an enhancement issue #12 to provide an easier way to recover the state database for such situations in the future.
